- cors.xml
- scripts/create-s3-distribution.sh
The settings should be applied manually :(
> Added CORS settings file for s3 bucket

- src/sass/_basics.scss
- src/sass/main.scss
Added basic styles to styleguide to make dev life easier
> Added basic styles to styleguide

- src/components/text/_text.scss
- src/components/text/text-bit.html
> mint-text-bit--dark added . Fixes #172

- src/components/text/_text.scss
- src/components/text/text-bit.html
- src/sass/_config.scss
> Refactor text bit

- src/components/subject-icons/_subject-icon.scss
- src/components/subject-icons/subjects.html
> Add mint subject icon small option

- src/components/labels/_labels.scss
- src/components/labels/labels.html
closes https://github.com/brainly/style-guide/issues/266
> Updated labels

- CONTRIBUTING.md
> Update build/merge flow in the docs

- src/components/popup-menu/popup-menu.html
- src/components/popup-menu/popup-menu.scss
- src/docs/_data/navigation.yml
- src/docs/_sass/_docs-block.scss
- src/sass/main.scss
> Create mint-popup-menu. Fixes #246

- Dockerfile
- scripts/run-scss-lint.sh
> Run scss-lint from docker

- CONTRIBUTING.md
- scripts/ide-run-scss-lint-from-docker.sh
- scripts/ide-scss-lint-exec.sh
- scripts/run-scss-lint.sh
- scripts/server.sh
- scripts/watch.sh
I have updated "server" and "watch" scripts to set proper container names for docker. I also added removing of container for "watch" script after hitting CTRL+C (it ). 
I also refactored 'ide-run-scss-lint-from-docker.sh' to get rid of duplicated code.
> Refactor scripts

- src/components/content-box/_content-box.scss
- src/components/footer/_footer.scss
- src/components/form-elements/_form-elements.scss
- src/components/header/_header.scss
- src/components/home-button/_home-button.scss
- src/components/logo/_logo.scss
- src/components/text/_text-bits.scss
- src/components/toplayer/_toplayer.scss
- src/sass/_config.scss
- src/sass/_helpers.scss
- src/sass/_mixins.scss
> Add mintBreakpoint mixin

- src/components/dropdowns/_dropdowns.scss
closes https://github.com/brainly/style-guide/issues/311
> Removed overflow

- src/docs/_sass/main.scss
Get rid of the collapsing margin issue on the h1. Fixes #319
> Move title down

- src/components/footer/footer.html
- src/components/list/list.html
This PR have to wait to finish others part of renaming project
> [Renaming] Misdeberes.es -> Brainly.lat

- src/docs/_includes/navigation.html
- src/docs/_layouts/default.html
- src/docs/_sass/_docs-block.scss
- src/docs/_sass/_navigation.scss
> Make VR lines and hole highlighting optional

- src/components/dropdowns/_dropdowns.scss
- src/sass/_mixins.scss
there was an issue on some viewports
before:
after:
> Dropdown rem to pixel

- src/components/box/box.html
- src/components/bubble/bubble.html
- src/components/content-box/_content-box.scss
- src/components/content-box/content-box.html
- src/components/text/_headers.scss
- src/components/toplayer/_toplayer.scss
- Renamed mint-content-box__footer to mint-content-box__actions
- Added --large for __title and __actions
- Added examples
> Breaking changes for content-box for large components

- src/components/form-elements/_form-elements.scss
> Improved small selects

- src/docs/_sass/_navigation.scss
> Update menu to display items in 2 columns

- src/components/buttons/buttons.html
- src/components/dropdowns/_dropdowns.scss
- src/components/dropdowns/dropdowns.html
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/_select.scss
- src/components/form-elements/checkbox-radio.html
- src/components/icons/_icons.scss
- src/components/list/_list.scss
- src/components/list/list.html
- src/components/promo-box/promo-box.html
- src/sass/_config.scss
> Fix icon sizes

- src/components/buttons/_buttons.scss
- src/components/dropdowns/dropdowns.html
- src/components/labels/_labels.scss
- src/components/labels/labels.html
Text by default is lowercase now
> Refactor labels

- src/components/badges/_badges.scss
- src/components/buttons/_buttons.scss
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/_select.scss
- src/components/form-elements/_text-input.scss
- src/components/form-elements/_textarea.scss
- src/components/labels/_labels.scss
- src/components/list/_list.scss
- src/components/promo-box/_promo-box.scss
- src/components/rating/_rating.scss
- src/components/tabs/_tabs.scss
- src/components/text/_headers.scss
- src/components/text/_links.scss
- src/components/text/_text-bits.scss
- src/components/text/_text.scss
- src/components/toplayer/_toplayer.scss
- src/docs/_sass/_color-box.scss
- src/docs/_sass/_docs-block.scss
- src/docs/_sass/_navigation.scss
- src/docs/_sass/main.scss
- src/sass/_config.scss
- src/sass/_fonts.scss
closes #304 
As we can't use bolder all font-weight are now set using variables to be consistent and to easy refactor/change it.
> Refactor font-weight

- src/components/dropdowns/_dropdowns.scss
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/checkbox-radio.html
- src/components/labels/_labels.scss
> Remove mint-checkbox-label - use mint-label instead

- gulpfile.js
- package.json
- scripts/find_scss_unused_variables.sh
> Add checking for unused variable to prepush hook and travis build

- src/components/box/_box.scss
- src/components/content-box/_content-box.scss
> fix mint-box__hole and update mint-content-box

- package.json
- scripts/tasks/sass-build.js
- scripts/tasks/sass-docs-build.js
> Add gulp-clean-css plugin

- src/components/dropdowns/dropdowns.html
> Fix dropdown example

- src/components/bubble/_bubble.scss
> Add --full-width for mint-bubble

- .gitignore
- scripts/tasks/svgs-generate.js
- src/docs/_layouts/default.html
- src/svg-polyfill.js
> Update icons embeding

- src/components/form-elements/_text-input.scss
- src/components/header/header.html
- src/components/search/_search.scss
- src/components/search/search.html
> Fix search

- src/components/icons/_icons.scss
closes https://github.com/brainly/style-guide/issues/438
> Fix issue with icons on opera mini

- src/components/form-elements/_checkbox-radio.scss
- src/components/labels/_labels.scss
closes https://github.com/brainly/style-guide/issues/482
closes https://github.com/brainly/style-guide/issues/481
> Fix opera mini issues

- src/components/icons/_icons.scss
- src/docs/_data/icons.yml
closes https://github.com/brainly/style-guide/issues/510
> Add mint-icon--gray

- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
> Added squared icon-as-button

- gulpfile.js
- scripts/tasks/fingerprint-replace.js
- scripts/tasks/watch-docs-templates.js
- src/components/separators/_horizontal-separator.scss
- src/components/separators/separators.html
- src/components/separators/small-device.html
> Added separator margins for small devices

- src/components/bubble/bubble.html
- src/components/content-box/content-box.html
- src/components/text/links.html
> Removed text-description usages from examples

- src/components/bubble/_bubble.scss
- src/components/bubble/bubble.html
> Added bubble modifiers

- src/components/text/_text-bits.scss
> Remove word breaking from text bit

- src/components/form-elements/_textarea.scss
> Changed textarea sizes to follow VR

- src/components/content-box/_content-box.scss
- src/components/content-box/content-box.html
> Added --spaced modifier for content box title/header

- src/components/form-elements/_checkbox-radio.scss
closes https://github.com/brainly/style-guide/issues/529
> Fix mint-radio breaking layout on opera mini

- src/components/text/_links.scss
- src/components/text/links.html
closes https://github.com/brainly/style-guide/issues/441
closes https://github.com/brainly/style-guide/issues/567
> Update mint link

- src/components/form-elements/_textarea.scss
closes https://github.com/brainly/style-guide/issues/581
> Update small textarea

- src/components/overlayed-box/_overlayed_box.scss
> Update overlayed box

- package.json
- tools/webpack.config.prod.js
* addded uglify plugin;
* added Occurence Order Plugin;
* added Dedupe Plugin;
* removed react-transform
> [Issue #492] added production config for webpack

- src/components/content-box/_content-box.scss
- src/components/content-box/content-box.html
Fixes #428 
I did not come up with a good example for that.
Any ideas?
> Added --full modifier for content-box__content

- src/components/header/_header.scss
- src/components/header/header.html
- src/components/header/small-device.html
- src/docs/_sass/main.scss
- src/sass/_config.scss
Fixes #435 
I've added an example with scrolling over the gradient for better illustration.
> Added --fixed modifier for header + example

- src/components/buttons/_buttons.scss
- src/components/colors/colors.html
- src/components/form-elements/_select.scss
- src/sass/_config.scss
Mateusz Tatara asked us to change graySecondary. After change I had to update the "select" component and change color of one of the buttons. I've also sorted gray colors in the styleguide.
BEFORE:
AFTER:
> Changing graySecondary, fixing select.

- src/components/progressbar/_progressbar.scss
- src/components/progressbar/progressbar.html
- src/docs/_data/navigation.yml
- src/sass/main.scss
> Progressbar component added

- src/components/avatar/avatar.html
- src/components/badges/badges.html
- src/components/content-box/content-box.html
- src/components/dropdowns/dropdowns.html
- src/components/footer/footer.html
- src/components/header/small-device.html
- src/components/popup-menu/popup-menu.html
- src/components/promo-box/promo-box.html
- src/components/separators/separators.html
- src/components/separators/small-device.html
- src/components/text/text-bit.html
- src/components/toplayer/notlogged_toplayer.html
- src/components/toplayer/toplayer.html
using https://gist.github.com/kdzwinel/426a0f76f113643fa285
fixes #423
> Remove deprecated CSS classes used in HTML but not defined in CSS anymore

- src/components/form-elements/_text-input.scss
closes https://github.com/brainly/style-guide/issues/616
> Update input placeholders

- src/components/progressbar/_progressbar.scss
- src/components/progressbar/progressbar.html
> Progressbar animation changed.

- README.md
- scripts/tasks/sass-build.js
Style guide size went from 50kb to 52kb (no gzip)
> Update browser stats and match autoprefixer settings

- src/components/buttons/_buttons.scss
> Update button primary round

- src/components/list/_list.scss
- src/components/list/list.html
> Add small modifier

- src/components/list/_list.scss
Closes https://github.com/brainly/style-guide/issues/413
> Add mint list modifier

- src/components/list/list.html
> Add list to example

- src/components/header/small-device.html
> fixed 404 on header example

- src/components/avatar/_avatar.scss
- src/components/avatar/avatar.html
> added xlarge avatar to examples

- LICENSE.md
As discussed with our lawyer.
@piotrpyznarski please take a look.
> License file added. Fixes #627

- package.json
- src/components/text/_headers.scss
- src/components/text/_text.scss
- src/components/text/text.html
- src/sass/_config.scss
closes https://github.com/brainly/style-guide/issues/455
closes https://github.com/brainly/style-guide/issues/459
closes https://github.com/brainly/style-guide/issues/674
closes https://github.com/brainly/style-guide/issues/610
> Small updates

- package.json
- src/components/box/_box.scss
- src/components/box/box.html
> Add mint-box--dark

- package.json
- src/components/list/_list.scss
- src/components/separators/_horizontal-separator.scss
- src/components/separators/_separators.scss
> Make all separator lines solid and make their color lighter

- package.json
- src/components/list/_list.scss
- src/components/list/list.html
> Add mint-menu-list--large

- package.json
- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
> Icon as button  mint

- package.json
- src/components/form-elements/_textarea.scss
- src/components/form-elements/textarea.html
> Fix textarea sizes

- package.json
- src/components/avatar/_avatar.scss
- src/components/content-box/content-box.html
closes https://github.com/brainly/style-guide/issues/449
🐔
> Add avatar--spaced modifier

- package.json
- src/components/avatar/_avatar.scss
https://crbug.com/157218
Fixes #715
> Workaround for the Chrome border-radius clipping bug

- package.json
- src/sass/_mixins.scss
- src/sass/_normalize.scss
- src/sass/_reset.scss
closes https://github.com/brainly/style-guide/issues/655
> Fix issue with new node sass

- package.json
- src/components/avatar/_avatar.scss
- src/components/box/_box.scss
- src/components/bubble/_bubble.scss
- src/components/buttons/_buttons_secondary.scss
- src/components/buttons/_icon-as-button.scss
- src/components/dropdowns/_dropdowns.scss
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/_select.scss
- src/components/form-elements/_text-input.scss
- src/components/form-elements/_textarea.scss
> Thin borders

- package.json
- src/components/buttons/_buttons-mixins.scss
- src/components/flash-messages/_flash-messages.scss
- src/components/flash-messages/flash-messages.html
- src/docs/_data/navigation.yml
- src/sass/main.scss
> Add flash-messages

- package.json
- src/components/badges/_badges.scss
- src/components/breadcrumbs/_breadcrumbs.scss
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/_buttons_primary.scss
- src/components/buttons/_buttons_primary_round.scss
- src/components/buttons/_buttons_secondary.scss
- src/components/content-box/_content-box.scss
- src/components/footer/_footer.scss
- src/components/form-elements/_text-input.scss
- src/components/header/_header.scss
- src/components/home-button/_home-button.scss
- src/components/list/_list.scss
- src/components/logo/_logo.scss
- src/components/popup-menu/popup-menu.scss
- src/components/separators/_horizontal-separator.scss
- src/components/text/_headers.scss
- src/components/text/_text-bits.scss
- src/components/text/_text.scss
- src/components/toplayer/_toplayer.scss
- src/sass/_config.scss
- src/sass/_fonts.scss
- src/sass/_helpers.scss
- src/sass/_mixins.scss
- src/sass/main.scss
> Remove mint word from vars

- package.json
- src/components/helpers/rwd.html
- src/sass/_config.scss
closes https://github.com/brainly/style-guide/issues/348
🍈
> Add medium-down breakpoint

- package.json
- src/components/media/_media.scss
- src/components/media/media.html
- src/docs/_data/navigation.yml
- src/sass/main.scss
closes https://github.com/brainly/style-guide/issues/431
🔦
> Add media container

- package.json
- src/components/list/_list.scss
closes https://github.com/brainly/style-guide/issues/631
> Center list__icon

- package.json
- src/sass/_config.scss
before:
after:
all components that use grey primary and secondary will be updated.
major or minor?
> Update main grey colors

- package.json
- src/components/header/_header.scss
- src/sass/_config.scss
> Update header max-width after layout resizing

- package.json
- src/components/box/_box.scss
- src/components/bubble/_bubble.scss
- src/components/media/_media.scss
- src/components/toplayer/_toplayer.scss
> Update border-radius on containers

- src/components/buttons/_buttons_secondary.scss
- src/components/colors/colors.html
- src/components/dropdowns/_dropdowns.scss
- src/components/form-elements/_select.scss
- src/components/list/_list.scss
- src/components/separators/_horizontal-separator.scss
- src/components/separators/_separators.scss
- src/docs/_sass/_color-box.scss
- src/sass/_config.scss
> Update gray secondary light color and merge gray secondary light and alt light

- src/components/layout/_layout.scss
- src/components/layout/layout.html
- src/components/layout/layout_large.html
- src/components/layout/layout_medium.html
- src/components/layout/layout_small.html
- src/docs/_data/navigation.yml
- src/sass/main.scss
> Add layout component

- package.json
- src/components/form-elements/_text-input.scss
- src/components/form-elements/text-input.html
> Update and clean text inputs

- package.json
- src/components/form-elements/_textarea.scss
- src/components/form-elements/textarea.html
> Update textarea component

- package.json
- src/components/header/header.html
- src/components/header/small-device.html
- src/components/popup-menu/popup-menu.html
- src/components/search/search.html
> Update inputs in header and search

- package.json
- src/components/form-elements/_select.scss
> Update color of select text

- npm-shrinkwrap.json
- package.json
- src/components/layout/_layout.scss
> Add align-items: flex-start on layout container on large screen

- package.json
- src/docs/_includes/navigation.html
- src/docs/_sass/_docs-block.scss
closes https://github.com/brainly/style-guide/issues/788
> VR ? What VR ? :O

- package.json
- src/components/text/_headers.scss
- src/components/text/headers.html
- src/sass/_mixins.scss
close https://github.com/brainly/style-guide/issues/448
> Update header secondary

- package.json
- src/docs/_includes/navigation.html
- src/docs/_sass/_navigation.scss
Searches menu items, behaves like a menu, navigable using tab.
> Add search to navigation.

- package.json
- src/components/footer/_footer.scss
- src/components/footer/footer.html
- src/components/logo/_logo.scss
- src/components/logo/logo.html
- src/components/text/_text-bits.scss
- src/components/text/text-bit.html
- src/docs/_sass/_docs-block.scss
> Remove small logo

- package.json
- src/docs/_includes/head.html
- src/docs/_layouts/items.html
- src/docs/_sass/_copy-helper.scss
- src/docs/_sass/main.scss
Clicking on any element will show its code. Clicking on the code will select it (doesn't work in FF) for easy copying.
Enjoy the motion picture below. Merge at will. See you in 2w 👋
> Markup copy helper v1

- package.json
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/_buttons_primary.scss
- src/components/buttons/_buttons_primary_round.scss
- src/components/buttons/_buttons_secondary.scss
> Update buttons styles

- package.json
- src/components/media/_media.scss
- src/components/media/media.html
- src/docs/_sass/_docs-block.scss
> Update media element

- package.json
- src/components/buttons/_buttons_secondary.scss
- src/components/buttons/buttons.html
closes https://github.com/brainly/style-guide/issues/806
> Add button secondary disabled

- package.json
- src/components/text/_text.scss
- src/components/text/text.html
closes https://github.com/brainly/style-guide/issues/802
> Update sg text

- package.json
- src/components/badges/_badges.scss
- src/components/badges/badges.html
- src/components/text/_text.scss
- src/components/text/text.html
> Badges, badgesss, badger!!!

- package.json
- src/components/rating/_rating.scss
- src/sass/_config.scss
closes https://github.com/brainly/style-guide/issues/566
> Small fixes + cleanup

- package.json
- src/components/rating/_rating.scss
closes https://github.com/brainly/style-guide/issues/830
> Fix active rating cursor

- package.json
- src/components/buttons/_icon-as-button.scss
- src/components/layout/_layout.scss
- src/components/layout/layout.html
- src/components/layout/layout_large.html
- src/components/layout/layout_reversed_order.html
- src/components/layout/layout_small.html
- src/components/toplayer/_toplayer.scss
- src/sass/_config.scss
> Implement layout box component

- package.json
- scripts/tasks/svgs-generate.js
- src/docs/_includes/head.html
- src/docs/_layouts/items.html
- src/svg-polyfill.js
Put icons on the top of the body and load them with async.
Enable SVGO to optimize svg images.
icons 24kb -> 18kb
subject-icons 114kb -> 71kb
> svgo + async icons

- package.json
- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
> Add gray secondary modifier of icon as a button

- package.json
- src/components/avatar/_avatar.scss
> Remove useless padding from avatar icon

- package.json
- src/components/popup-menu/popup-menu.scss
> Make smaller arrow in popup menu

- package.json
- src/components/text/_headers.scss
- src/components/text/_text.scss
- src/components/text/text.html
- src/sass/_config.scss
> Update font sizes

- package.json
- src/components/box/_box.scss
- src/components/box/box.html
closes https://github.com/brainly/style-guide/issues/865
> Add mint modifier for box

- package.json
- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
> Icon as button update - adding transparent version to action buttons.

- package.json
- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
> Icon-as-button - removing square buttons.

- package.json
- src/components/avatar/avatar.html
- src/components/box/box.html
- src/components/bubble/bubble.html
- src/components/content-box/content-box.html
- src/components/header/header.html
- src/components/header/small-device.html
- src/components/media/media.html
- src/components/overlayed-box/overlayed-box.html
- src/components/popup-menu/popup-menu.html
- src/components/separators/separators.html
> Unspash update.

- package.json
- src/components/flash-messages/_flash-messages.scss
- src/components/flash-messages/flash-messages.html
> Update flash messages

- package.json
- src/components/buttons/_icon-as-button.scss
> Gray light icon as a button

- package.json
- src/components/toplayer/_toplayer.scss
> Top layer update

- package.json
- src/components/avatar/_avatar.scss
- src/components/avatar/avatar.html
- src/components/content-box/content-box.html
- src/components/header/header.html
- src/components/media/media.html
- src/components/overlayed-box/overlayed-box.html
- src/components/separators/separators.html
- src/components/separators/small-device.html
> Reverse avatar colors.

- package.json
- src/components/layout/_layout.scss
fixes https://github.com/brainly/style-guide/issues/892
> Fix layout on mobile

- package.json
- src/components/header/_header.scss
> Box shadow for header.

- package.json
- src/components/separators/_separators.scss
- src/components/separators/separators.html
- src/components/text/_text-bits.scss
- src/components/text/text-bit.html
> Text bit improvement and large separator

- src/components/badges/_badges.scss
- src/components/box/_box.scss
- src/components/bubble/_bubble.scss
- src/components/buttons/_buttons_primary_round.scss
- src/components/buttons/_buttons_secondary.scss
- src/components/dropdowns/_dropdowns.scss
- src/components/form-elements/_select.scss
- src/components/form-elements/_text-input.scss
- src/components/form-elements/_textarea.scss
- src/components/layout/_layout.scss
- src/components/media/_media.scss
- src/components/popup-menu/popup-menu.scss
- src/components/toplayer/_toplayer.scss
- src/docs/_sass/_color-box.scss
- src/sass/_config.scss
> border-radius refactor.

- src/components/buttons/buttons.html
> Removing not-used rating buttons.

- package.json
- src/components/colors/colors.html
- src/components/layout/_layout.scss
- src/components/media/_media.scss
- src/docs/_data/colors.yml
- src/sass/_config.scss
- Update of existing colors
- Adding new special colors to the palet.
Before:
After:
> Colors update

- package.json
- src/components/action-list/action-list.html
- src/components/action-list/action-list.scss
- src/docs/_data/navigation.yml
- src/sass/main.scss
> Action list vol.1

- package.json
- src/components/avatar/_avatar.scss
- src/components/avatar/avatar.html
> Add avatar xsmall option

- package.json
- src/components/box/_box.scss
- src/components/box/box.html
> Add box modifiers

- package.json
- src/components/content-box/_content-box.scss
- src/components/content-box/content-box.html
> sg-content-box additional spacings

- package.json
I forgot to create .2 before creating a tag
> Bump version :(

- README.md
UCBrowser, Edge and Android Webview are new
> Update browser stats and link to the source.

- package.json
- src/components/labels/_labels.scss
- src/components/labels/labels.html
closes https://github.com/brainly/style-guide/issues/965
> Add elements-to-the-top modifier to label

- package.json
- src/components/form-elements/_text-input.scss
- src/components/header/_header.scss
- src/components/header/header.html
- src/components/header/small-device.html
- src/components/search/_search.scss
- src/components/search/search.html
- src/sass/_config.scss
> Change position of search icon

- package.json
- src/components/footer/_footer.scss
- src/components/footer/footer.html
> Footer light

- package.json
- src/components/footer/_footer.scss
Fix for max width for footer container
Fix for background color for new footer
> Fix for footer container

- package.json
- src/components/dropdowns/_dropdowns.scss
- src/components/dropdowns/dropdowns.html
> Dropdown fixed

- package.json
- src/components/toplayer/_toplayer.scss
- src/components/toplayer/splash_screen_toplayer.html
closes https://github.com/brainly/style-guide/issues/972
> Add limited-width modifier to toplayer

- package.json
- src/docs/_data/colors.yml
- src/sass/_config.scss
> Update mintPrimary to brand new one

- package.json
- src/components/overlay/_overlay.scss
closes https://github.com/brainly/style-guide/issues/982
> Fix overlay scrolling on iOS

- package.json
- src/components/colors/colors.html
- src/docs/_data/colors.yml
- src/sass/_config.scss
> Color pallet update

- src/components/form-elements/_text-input.scss
- src/components/form-elements/text-input.html
> Input update

- package.json
- src/components/dropdowns/_dropdowns.scss
- src/components/dropdowns/dropdowns.html
- src/components/form-elements/_select.scss
- src/components/form-elements/select.html
> Selects update

- package.json
- src/components/dropdowns/_dropdowns.scss
- src/components/dropdowns/dropdowns.html
> Arrow icon

- package.json
- src/components/dropdowns/_dropdowns.scss
> Fixing arrow position

- package.json
- src/components/dropdowns/_dropdowns.scss
- src/components/form-elements/_select.scss
- src/components/form-elements/_text-input.scss
- src/components/search/search.html
Fixing border radius according to buttons
Removing not used search modifier
improvements for dropdowns
improvements for selects
> Dropdown update again

- package.json
- src/components/form-elements/_text-input.scss
New version 🤡
And valid is still valid 🙄
> Inputs fix

- .eslintignore
- .eslintrc
- .gitignore
- package.json
- src/components/buttons/pages/buttonsReact.jsx
- src/components/buttons/pages/buttonsReact2.jsx
- yarn.lock
> Add eslint

- package.json
- src/components/box/_box.scss
- src/components/box/box.html
> Adding navyblue box

- package.json
- src/components/header/_header.scss
Remove hardcoded height for topbar.
> Fix styles for header

- README.md
- src/components/bubble/Bubble.jsx
- src/components/bubble/bubble.spec.jsx
- src/components/bubble/pages/bubble.jsx
* extract constants from module
* update tests and examples
* update readme
> Bubble refactor

- package.json
- src/components/action-list/action-list.html
- src/components/action-list/action-list.scss
> Action list centered

- gulpfile.js
- package.json
- scripts/tasks/build-copy-components.js
- scripts/tasks/build-copy-package-json.js
- scripts/tasks/clean-dist.js
- scripts/tasks/docs-copy-components.js
- scripts/tasks/fingerprint-replace.js
- scripts/tasks/fingerprint.js
- scripts/tasks/index-fingerprint-replace.js
- scripts/tasks/jekyll-docs.js
- scripts/tasks/root-redirect-page.js
- scripts/tasks/sass-build.js
- scripts/tasks/sass-docs-build.js
- scripts/tasks/svgs-generate.js
- scripts/tasks/upload-files.js
- scripts/tasks/watch-copy-components.js
- scripts/tasks/watch-docs-sass.js
- scripts/tasks/watch-docs-templates.js
- scripts/tasks/watch-react-pages.js
- scripts/tasks/watch-sass.js
* reformat files
* create watch-copy-components
* reformat watch system files
> Gulp watch fix

- package.json
- src/components/avatar/pages/avatar.jsx
- src/components/buttons/pages/buttons.jsx
- src/components/dropdowns/pages/dropdowns.jsx
- src/components/icon-as-button/pages/icon-as-button.jsx
- src/components/icons/pages/icons.jsx
- src/components/popup-menu/pages/popup-menu.jsx
- src/docs/ContrastBox.jsx
- src/docs/DocsBlock.jsx
- src/docs/_sass/_docs-block.scss
* deleted unused styles
* create ContrastBox.jsx component
* add missing properties
* replace to new component
> Docs block refactor

- package.json
- scripts/tasks/build-react-pages.js
- yarn.lock
* add gulp-prettify
* no more 1 line html from react
> Pretty generated html

- package.json
> v85.4.0, Subject icons react

- package.json
- src/components/buttons/_buttons_primary_round.scss
Primary round button color blue -> green
> Primary round button color blue -> green

- package.json
- src/components/box/pages/box.jsx
- src/components/bubble/pages/bubble.jsx
- src/components/content-box/contentBox.spec.jsx
- src/components/list/pages/list.jsx
- src/components/toplayer/pages/default_toplayer.jsx
- src/components/toplayer/pages/notlogged_toplayer.jsx
- src/components/toplayer/pages/small_spaced_toplayer.jsx
- src/components/toplayer/pages/splash_screen_toplayer.jsx
- src/components/toplayer/pages/toplayer.jsx
- src/docs/DocsBlock.jsx
Using `<ContentBox>` in the styleguide
> Using <ContentBox>

- package.json
- src/components/action-list/pages/action-list.jsx
- src/components/box/pages/box.jsx
- src/components/breadcrumbs/pages/breadcrumbs.jsx
- src/components/bubble/pages/bubble.jsx
- src/components/content-box/pages/content-box.jsx
- src/components/flash-messages/FlashMessage.jsx
- src/components/list/ListItem.jsx
- src/components/media/pages/media.jsx
- src/components/text/Text.jsx
- src/components/toplayer/pages/notlogged_toplayer.jsx
- src/components/toplayer/pages/small_spaced_toplayer.jsx
* `<Text`, `<TextBit>`, `<Link>`, `<HeaderPrimary>`, `<HeaderSecondary>`
* iconTypes → ICON_TYPE
* iconColors → ICON_COLOR
* buttonSecondaryTypes → BUTTON_SECONDARY_TYPE
* buttonPrimaryTypes → BUTTON_PRIMARY_TYPE
> Using <Text> react components

- package.json
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/checkbox-radio.html
> Checkbox and radio style

- package.json
- src/components/subject-icons/SubjectIconBox.jsx
- src/components/subject-icons/SubjectIconBox.spec.jsx
- src/components/subject-icons/pages/subjects.jsx
> Subject icon box component

- package.json
- src/components/bubble/pages/bubble.jsx
- src/docs/_sass/_docs-block.scss
Removed .sg-bubble__hole as it didn't do anything
Closes #1105
> Removed bubble__hole

- package.json
- src/components/form-elements/Radio.jsx
- src/components/form-elements/Radio.spec.jsx
- src/components/form-elements/pages/checkbox.jsx
- src/components/form-elements/pages/radio.jsx
> Form elements react components - Radio

- package.json
- src/components/box/Box.jsx
- src/components/box/Box.spec.jsx
- src/components/box/_box.scss
- src/components/box/pages/box.jsx
> Add --peach and xsmall-padding to sg-box

- package.json
- src/components/form-elements/Select.jsx
- src/components/form-elements/_select.scss
(I will update the sg version and fix it in all our projects)
Closes #1107
> CSS arrow instead of svg

- package.json
- src/components/text/Link.jsx
- src/components/text/Link.spec.jsx
* no href → span 
* disabled → span with .disabled class
* href → working link
> Link refactor

- package-lock.json
- package.json
- src/components/bubble/pages/bubble.jsx
- src/components/content-box/pages/content-box.jsx
- src/components/footer/pages/footer.jsx
- src/components/list/List.jsx
- src/components/overlayed-box/pages/overlayed-box.jsx
- src/components/popup-menu/pages/popup-menu.jsx
- src/components/text/pages/links.jsx
- src/components/toplayer/iframe-pages/default_toplayer.jsx
- src/components/toplayer/iframe-pages/notlogged_toplayer.jsx
- src/components/toplayer/iframe-pages/small_spaced_toplayer.jsx
- src/components/toplayer/iframe-pages/splash_screen_toplayer.jsx
Using react components in the styleguide
* List - list icon color & type
Closes #1118
> Components usage

- README.md
- package-lock.json
- package.json
- src/docs/README.md
Removed info about Jekyll
Closes #1125
> README update

- package-lock.json
- package.json
- src/components/search/_search.scss
(it is not used anywhere)
Closes #971
> Remove .sg-search--short style

- package-lock.json
- package.json
- src/components/text/Text.jsx
- src/components/text/_text.scss
- src/components/text/pages/text.jsx
> .sg-text--large

- package-lock.json
- package.json
- src/components/box/Box.jsx
- src/components/box/Box.spec.jsx
- src/components/box/_box.scss
- src/components/box/pages/box.jsx
> Box with shadow

- package-lock.json
- package.json
- src/components/form-elements/pages/text-input.jsx
> text input fix

- package-lock.json
- package.json
- src/components/form-elements/Select.jsx
- src/components/form-elements/Select.spec.jsx
- src/components/form-elements/TextInput.jsx
- src/components/form-elements/TextInput.spec.jsx
- src/components/form-elements/Textarea.jsx
- src/components/form-elements/Textarea.spec.jsx
- src/components/form-elements/pages/text-input.jsx
- src/components/form-elements/pages/textarea.jsx
- src/components/search/Search.spec.jsx
* true/false → valid, invalid
Closes #1141
> Inputs validation

- src/components/subject-mono-icons/pages/subject-mono-icons.jsx
- src/docs/layouts/ItemsPage.jsx
- src/docs/pages/index.jsx
Small improvements to the index page.
> Fix paths to DocsBlock & ContrastBox component.

- package.json
- src/components/avatar/pages/avatar-interactive.jsx
- src/components/badges/pages/badges-interactive.jsx
- src/components/bubble/pages/bubble-interactive.jsx
- src/docs/components/ComponentSettings.jsx
- src/docs/components/ComponentSettingsInput.jsx
- src/docs/components/ComponentSettingsSelect.jsx
- src/docs/components/DocsActiveBlock.jsx
- src/docs/page-components.jsx
- read default values from the component and update settings form accordingly
- use settings keys instead of values in the settings form
- refactor ComponentSettings
- create interactive page for badges
> Interactive improvements

- package.json
- src/components/form-elements/Checkbox.jsx
- src/components/form-elements/Radio.jsx
- src/docs/_sass/_docs-active-block.scss
- src/docs/_sass/_docs-block.scss
- src/docs/components/ComponentSettings.jsx
- src/docs/components/ComponentSettingsInput.jsx
- src/docs/components/ComponentSettingsSelect.jsx
- src/docs/components/DocsActiveBlock.jsx
- src/docs/components/DocsActiveBlockSettings.jsx
- yarn.lock
> Interactive improvements - 💄

- package.json
- src/components/form-elements/Input.jsx
- src/components/form-elements/Input.spec.jsx
- src/components/form-elements/pages/text-input.jsx
- src/components/search/Search.jsx
- src/components/search/Search.spec.jsx
- src/docs/components/ComponentSettingsInput.jsx
TextInput → Input
value: string or number
> Input refactor

- package.json
- src/components/toplayer/TopLayer.jsx
- src/components/toplayer/_toplayer.scss
> 	Remove useless header in toplayer component

- package.json
- src/components/avatar/pages/avatar-interactive.jsx
- src/components/badges/pages/badges-interactive.jsx
- src/components/bubble/pages/bubble-interactive.jsx
- src/components/buttons/pages/buttons-interactive.jsx
- src/docs/components/ComponentSettings.jsx
- src/docs/components/ComponentSettingsSelect.jsx
- src/docs/components/DocsActiveBlock.jsx
- src/docs/components/JSXGenerator.js
- src/docs/page-components.jsx
Buttons section:
Show "(default)" value where prop is not required:
> Interactive buttons

- package.json
- src/components/buttons/ButtonSecondary.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/_select.scss
- src/components/form-elements/_textarea.scss
* Textarea looks more like inputs
* Select - 2px padding
* ButtonSecondary - removed unused prop
Before:
After:
> Form elements style

- package.json
- src/components/dropdowns/_dropdowns.scss
> Fix hove color for dropdowns

- package-lock.json
- package.json
- src/docs/_sass/_docs-active-block.scss
- src/docs/components/DocsActiveBlock.jsx
- src/docs/components/DocsActiveBlockSettings.jsx
> DocsActiveBlock style

- package-lock.json
- package.json
- src/components/flash-messages/pages/flash-messages-interactive.jsx
- src/docs/page-components.jsx
> Interactive flash messages

- package.json
- src/components/stickers/pages/stickers-interactive.jsx
- src/components/subject-icons/pages/subject-icons-interactive.jsx
- src/components/subject-mono-icons/pages/subject-mono-icons-interactive.jsx
- src/docs/layouts/ItemsInteractivePage.jsx
- src/docs/page-components.jsx
> Stickers & subject icons - interactive

- package.json
- src/components/action-list/pages/action-list-interactive.jsx
- src/components/box/pages/box-interactive.jsx
- src/components/rating/pages/rating-interactive.jsx
- src/docs/page-components.jsx
Closes #1172
Closes #1193
Closes #1188
> Demo pages - boxes, action lists, ratings

- package.json
- src/docs/_sass/_copy-helper.scss
- src/docs/components/CodeBlock.jsx
> Copy code button

- package.json
- src/components/stickers/pages/stickers-interactive.jsx
- src/components/subject-icons/SubjectIconBox.jsx
- src/components/subject-icons/SubjectIconBox.spec.jsx
- src/components/subject-icons/pages/subject-icons-interactive.jsx
- src/components/subject-icons/pages/subjects-interactive.jsx
- src/components/subject-icons/pages/subjects.jsx
- src/components/subject-mono-icons/pages/subject-mono-icons-interactive.jsx
- src/docs/page-components.jsx
SubjectIconBox
before:
```
<SubjectIconBox>
<SubjectIcon type={TYPE.LIFE_SCIENCE}/>
</SubjectIconBox>
```
after:
```
<SubjectIconBox type={TYPE.LIFE_SCIENCE}/>
```
Closes #1183
> Subjects interactive

- package.json
- src/components/icons/pages/icons-interactive.jsx
- src/docs/page-components.jsx
before:
`import Avatars from '../components/avatar/pages/avatar-interactive';`
after: 
`import Avatars from 'avatar/pages/avatar-interactive';`
Closes #1162
> Interactive icons + import refactor

- package.json
- src/components/layout/_layout.scss
fixes https://github.com/brainly/style-guide/issues/864
> Update layout add $includeHtml

- package.json
- src/components/dropdowns/pages/dropdowns.jsx
- src/components/separators/pages/separators-interactive.jsx
- src/docs/_sass/_docs-active-block.scss
- src/docs/components/DocsActiveBlock.jsx
- src/docs/page-components.jsx
> Interactive separators

- package.json
- src/components/labels/pages/labels-interactive.jsx
- src/docs/page-components.jsx
> interactive labels

- package.json
- src/components/icons/pages/icons-interactive.jsx
- src/docs/components/DocsActiveBlock.jsx
`  <DocsActiveBlock settings={settings} backgroundColor={BACKGROUND_COLOR.DARK}>`
> change background color in docs active block

- package.json
- src/components/popup-menu/pages/popup-menu-interactive.jsx
- src/components/popup-menu/pages/popup-menu.jsx
- src/docs/components/CodeBlock.jsx
- src/docs/components/JSXGenerator.js
- src/docs/components/JSXGenerator.spec.jsx
- src/docs/page-components.jsx
> Popups interactive

- package.json
- src/components/text/HeaderPrimary.jsx
- src/components/text/HeaderSecondary.jsx
- src/components/text/pages/headers-interactive.jsx
- src/components/text/pages/links-interactive.jsx
- src/components/text/pages/text-bit-interactive.jsx
- src/components/text/pages/text-interactive.jsx
- src/docs/page-components.jsx
Closes #1158 
Closes #1161 
Closes #1159 
Closes #1160
> Interactive text

- package.json
- src/components/list/pages/list-interactive.jsx
- src/docs/page-components.jsx
> List interactive

- package.json
- src/components/breadcrumbs/pages/breadcrumbs-interactive.jsx
- src/components/breadcrumbs/pages/breadcrumbs.jsx
- src/docs/page-components.jsx
> interactive breadcrumbs

- package.json
- src/components/header/pages/header-interactive.jsx
- src/docs/page-components.jsx
Fixed header:
**It's not a bug, it's a feature! 😂** If we use Iframe we can't change anything
Closes #1191
> interactive header

- package.json
- src/components/action-list/ActionList.jsx
- src/components/avatar/Avatar.jsx
- src/components/badges/Badge.jsx
- src/components/flash-messages/FlashMessage.jsx
- src/components/form-elements/Checkbox.jsx
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icons/Icon.jsx
- src/components/labels/Label.jsx
- src/components/list/List.jsx
- src/components/rating/Rating.jsx
- src/components/search/Search.jsx
- src/components/stickers/Sticker.jsx
- src/components/toplayer/TopLayer.jsx
> Change path in components

- package.json
- src/components/footer/FooterLine.jsx
- src/components/footer/pages/footer-interactive.jsx
- src/components/layout/pages/layout-interactive.jsx
- src/docs/_sass/_docs-active-block.scss
- src/docs/components/DocsActiveBlock.jsx
- src/docs/page-components.jsx
> Interactive footer & layout

- package.json
- src/components/toplayer/pages/toplayer-interactive.jsx
- src/components/toplayer/pages/toplayer.jsx
- src/docs/_sass/_docs-active-block.scss
- src/docs/page-components.jsx
> interactive toplayer

- package.json
- src/components/action-list/ActionList.jsx
- src/components/avatar/Avatar.jsx
- src/components/badges/Badge.jsx
- src/components/box/Box.jsx
- src/components/breadcrumbs/Breadcrumb.jsx
- src/components/bubble/Bubble.jsx
- src/components/buttons/ButtonPrimary.jsx
- src/components/buttons/ButtonRound.jsx
- src/components/buttons/ButtonSecondary.jsx
- src/components/content-box/ContentBox.jsx
- src/components/content-box/ContentBoxActions.jsx
- src/components/content-box/ContentBoxContent.jsx
- src/components/content-box/ContentBoxHeader.jsx
- src/components/content-box/ContentBoxTitle.jsx
- src/components/dropdowns/Dropdown.jsx
- src/components/flash-messages/FlashMessage.jsx
pass custom className to the components
> custom class name, part 1

- package.json
- src/components/form-elements/Checkbox.jsx
> uuid set only once

- package.json
- src/components/home-button/HomeButton.jsx
- src/components/logo/Logo.jsx
- src/components/logo/pages/logo-interactive.jsx
- src/docs/page-components.jsx
> interactive logo

- package.json
- src/components/overlayed-box/pages/overlayed-box-interactive.jsx
- src/docs/page-components.jsx
> interactive overlayed box

- package.json
- src/components/box/Box.spec.jsx
- src/docs/components/ContrastBox.spec.jsx
- src/docs/components/DocsBlock.jsx
- src/docs/components/DocsBlock.spec.jsx
- src/docs/components/JSXGenerator.spec.jsx
DocsBlock, ContrastBox and JSXGenerator - 100% coverage
Closes #1134
> Docs tests

- package.json
- src/components/media/pages/media-interactive.jsx
- src/docs/page-components.jsx
> interactive media

- package.json
- src/components/helpers/pages/rwd-interactive.jsx
- src/docs/page-components.jsx
> Interactive helpers

- package.json
- scripts/tasks/watch-docs-templates.js
> interactive pages watch

- package.json
- src/components/text/Text.jsx
> Text with --undefined class bug fix

- package.json
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icon-as-button/_icon-as-button.scss
* Border + adaptive = bad border color
* action + adaptive + active = background was primary color, not adaptive
* I'm not sure what to do with this one, but white icon on white background doesn't make sense
* transparent + active + colors(adaptive, gray, gray-secondary, gray-light, dark ) = not defined
* add mustard and lavender IconAsButton colors, with border, action, transparent etc
Closes #1018
> Icon as button styles

- package.json
- src/components/icon-as-button/_icon-as-button.scss
- src/components/icon-as-button/pages/icon-as-button.jsx
> Icon as button fixes

- package.json
- src/components/icon-as-button/IconAsButton.jsx
- src/docs/components/DocsActiveBlock.jsx
- src/docs/components/JSXGenerator.js
- src/docs/components/JSXGenerator.spec.jsx
> JSX generator without default props

- package.json
- src/components/dropdowns/Dropdown.jsx
- src/components/list/List.jsx
- src/components/list/MenuList.jsx
- src/docs/components/DocsActiveBlock.jsx
- src/docs/components/JSXGenerator.js
no need to pass propsWithDefaults to JSXGenerator
> JSXGenerator refactor ⚙

- package.json
- src/sass/_fonts.scss
closes https://github.com/brainly/style-guide/issues/751
> Add font-display: swap

- .travis.yml
Yarn takes ~70sec on Travis ATM, this might help
[EDIT] Down to ~30sec
> Add yarn cache preservation on travis

- package.json
- src/docs/components/JSXGenerator.js
- src/docs/components/JSXGenerator.spec.jsx
> JSXGenerator - prop without ={true}

- package.json
- src/docs/components/ComponentSettings.jsx
> Fix bind issue in ComponentSettings

- package.json
- src/docs/components/DocsActiveBlockSettings.jsx
> fixed bind issue in DocsActiveBlockSettings

- .travis.yml
new yarn 1.0 case badly download dependencies 
Now on SG will be fixed version of yarn (0.27)
> fix build on travis by downgrade version of yarn

- package.json
- src/components/buttons/ButtonPrimary.jsx
- src/components/buttons/ButtonSecondary.jsx
- src/components/buttons/pages/buttons-interactive.jsx
> Button as link

- .travis.yml
- package.json
- yarn.lock
running npm script eslint now pointing to correct eslint module in frontend-tools-config
update yarn on travis to 1.0.1
> Eslint yarn fix

- package.json
- src/components/subject-icons/SubjectIcon.jsx
- src/components/subject-icons/SubjectIcon.spec.jsx
- src/components/subject-icons/_subject-icon.scss
- src/components/subject-icons/pages/subject-icons-interactive.jsx
- src/components/subject-icons/pages/subject-mono-icons.jsx
> subject mono icon - change color

- package.json
we need to pass options to script 'eslint' by --
> fix running eslint

- package.json
- src/components/form-elements/Textarea.jsx
- src/components/form-elements/Textarea.spec.jsx
> textarea upgrade

- package.json
- src/components/action-list/ActionList.spec.jsx
- src/components/action-list/ActionListHole.jsx
- src/components/action-list/ActionListHole.spec.jsx
- src/components/action-list/action-list.scss
- src/components/action-list/pages/action-list.jsx
Interactive setup does not accept children settings modifications - see #1292
> Update Action List Hole

- Dockerfile
- package.json
give 'v' to github tag in frontend-tools-configs
> fix frontend-tools-configs in SG

- package.json
- src/components/buttons/ButtonSecondary.jsx
- src/components/buttons/ButtonSecondary.spec.jsx
> fix sg-button-secondary - disabled

- package.json
- src/components/buttons/ButtonSecondary.jsx
- src/components/buttons/ButtonSecondary.spec.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/_buttons_secondary.scss
Removed .sg-button-secondary--active-inverse-disabled class
Closes #1296
> Button active inverse

- package.json
- src/components/content-box/pages/content-box-interactive.jsx
- src/docs/page-components.jsx
We can either stick with this one example or create an interactive component for **every** type of content box - actions, title etc.
Closes #1194
> interactive content box

- package.json
- src/components/list/List.spec.jsx
- src/components/list/subcomponents/ListItem.jsx
List - no default icon 
List - no default icon  update tests
> List - no default icon

- package.json
- src/components/list/pages/list.jsx
List add iconType={ICON_TYPE.ARROW_RIGHT} in examples
> List examples fix

- package.json
- src/components/dropdowns/DropdownContainer.jsx
- src/docs/components/DocsActiveBlock.jsx
* add defaultProps to DropdownContainer
> Docs fix warning from proptypes, add defaultProps

- src/components/action-list/action-list.scss
> fix action list hole styles

- src/components/header/Header.jsx
- src/components/header/Header.spec.jsx
- src/components/header/HeaderContainer.jsx
- src/components/header/HeaderContainer.spec.jsx
- src/components/header/_header.scss
- src/components/header/iframe-pages/small-device.jsx
- src/components/header/pages/header-interactive.jsx
- src/components/header/pages/header.jsx
`sg-header` has no backgrond color anymore
`sh-header__container` has default color and `--light` modifier now
> Remove sg-header--light, Add sg-header__container--light

- package.json
- src/components/home-button/HomeButton.jsx
- src/components/home-button/_home-button.scss
- src/components/home-button/pages/home-button.jsx
> Add brainly-plus modifier to home-button

- package.json
- src/components/header/HeaderContainer.jsx
- src/components/header/HeaderContent.jsx
- src/components/header/HeaderContent.spec.jsx
- src/components/header/_header.scss
- src/components/header/iframe-pages/small-device.jsx
- src/components/header/pages/header-interactive.jsx
- src/components/header/pages/header.jsx
use-case: content that has its own margins/paddings
> Add --auto-height modifier to sg-header__content element

- package.json
- src/components/toplayer/TopLayer.jsx
- src/components/toplayer/TopLayer.spec.jsx
> click fn in toplayer

- package.json
- src/components/content-box/ContentBox.jsx
- src/components/content-box/ContentBox.spec.jsx
- src/components/content-box/ContentBoxActions.spec.jsx
- src/components/content-box/ContentBoxContent.spec.jsx
- src/components/content-box/ContentBoxHeader.spec.jsx
- src/components/content-box/ContentBoxTitle.spec.jsx
> Extend content box react component

- src/components/action-list/action-list.scss
space between - no changing margins
to left - change only needed margins + first child correct margin
> action list fixing

- package.json
- src/components/rating/Rating.jsx
- src/components/rating/Rating.spec.jsx
- src/components/rating/_rating.scss
- src/components/rating/pages/rating-interactive.jsx
- src/components/rating/subcomponents/Star.jsx
> Rating % value

- .gitignore
- CONTRIBUTING.md
- MAINTAINERS
- README.md
Simplify readme files, make them a bit more friendly, remove BEM docs, update maintainers, update browser stats, remove outdated docker file.
> Cleanup readme

- package.json
- src/components/buttons/pages/buttons-interactive.jsx
> Fix interactive buttons

- package.json
- src/components/rating/_rating.scss
> rating ie 11 fix

- package.json
- src/components/action-list/pages/action-list.jsx
- src/components/box/pages/box-interactive.jsx
- src/components/box/pages/box.jsx
- src/components/content-box/pages/content-box-interactive.jsx
- src/components/content-box/pages/content-box.jsx
- src/components/text/HeaderPrimary.jsx
- src/components/text/HeaderPrimary.spec.jsx
- src/components/text/HeaderSecondary.jsx
- src/components/text/HeaderSecondary.spec.jsx
- src/components/text/headerConsts.js
- src/components/text/pages/headers-interactive.jsx
- src/components/text/pages/headers.jsx
- src/components/toplayer/iframe-pages/notlogged_toplayer.jsx
- src/components/toplayer/iframe-pages/small_spaced_toplayer.jsx
- src/components/toplayer/pages/toplayer-interactive.jsx
- src/components/toplayer/pages/toplayer.jsx
COLOR -> HEADER_COLOR #1334
SIZE -> HEADER_SIZE #1333
TYPE -> HEADER_TYPE #1331
all exports defined in 1 place
> refactor exports in Headers

- package.json
- src/components/text/Text.jsx
- src/components/text/Text.spec.jsx
- src/components/text/_text.scss
- src/components/text/pages/text-interactive.jsx
- src/components/text/pages/text.jsx
closes https://github.com/brainly/style-guide/issues/1341
> Extend text element

- package.json
- src/components/action-list/ActionListHole.jsx
- src/components/action-list/ActionListHole.spec.jsx
- src/components/action-list/action-list.scss
- src/components/action-list/pages/action-list.jsx
> Extend action list hole

- package.json
- src/components/action-list/ActionList.jsx
- src/components/avatar/Avatar.jsx
- src/components/badges/Badge.jsx
- src/components/box/Box.jsx
- src/components/bubble/Bubble.jsx
- src/components/buttons/ButtonPrimary.jsx
- src/components/buttons/ButtonSecondary.jsx
- src/components/flash-messages/FlashMessage.jsx
- src/components/form-elements/Input.jsx
- src/components/form-elements/Textarea.jsx
- src/components/helpers/RwdHelper.jsx
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icons/Icon.jsx
- src/components/labels/Label.jsx
- src/components/list/MenuList.jsx
- src/components/logo/Logo.jsx
- src/components/math-symbols/MathSymbol.jsx
- src/components/separators/SeparatorHorizontal.jsx
- src/components/separators/SeparatorVertical.jsx
- src/components/subject-icons/SubjectIcon.jsx
- src/components/text/Link.jsx
- src/components/text/Text.jsx
- src/components/text/TextBit.jsx
- src/components/toplayer/TopLayer.jsx
tree shaking in SG
Simple objects exports
no reexports included in this PR
> tree shaking pt1

- package.json
- src/components/search/_search.scss
> Search fix ios

- package.json
- src/components/action-list/ActionListHole.jsx
- src/components/action-list/ActionListHole.spec.jsx
- src/components/action-list/pages/action-list.jsx
> Space bellow added into action list hole

- package.json
- src/components/box/Box.jsx
- src/components/box/_box.scss
> Box mint secondary light

- package.json
- src/components/card/Card.jsx
- src/components/card/Card.spec.jsx
- src/components/card/CardHole.jsx
- src/components/card/CardHole.spec.jsx
- src/components/card/_card.scss
- src/components/card/pages/card-interactive.jsx
- src/components/card/pages/card.jsx
- src/docs/navigation.js
- src/docs/page-components.jsx
- src/sass/main.scss
> Card component

- package.json
- src/components/list/MenuList.jsx
- src/components/list/MenuList.spec.jsx
- src/components/list/subcomponents/MenuItem.jsx
Menu item upgrade 
* add possibility to define link Type
> Menu item upgrade 

- package.json
- src/components/buttons/ButtonPrimary.jsx
- src/components/buttons/ButtonSecondary.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/pages/buttons.jsx
> Adding peach button

- package.json
- src/components/box/Box.jsx
- src/components/box/Box.spec.jsx
- src/components/box/_box.scss
- src/components/box/pages/box.jsx
> Extend box

- package.json
- src/components/action-list/ActionList.jsx
- src/components/action-list/ActionList.spec.jsx
- src/components/action-list/action-list.scss
- src/components/action-list/pages/action-list-interactive.jsx
- src/components/action-list/pages/action-list.jsx
> Add ALIGNMENT baseline to ActionList

- package.json
- src/components/separators/SeparatorVertical.jsx
- src/components/separators/_separators.scss
- src/components/separators/pages/separators.jsx
> Add full modifier to SeparatedVertical

- package.json
- src/components/action-list/ActionListHole.jsx
- src/components/action-list/action-list.scss
- src/components/action-list/pages/action-list.jsx
> Add stretch modifier to ActionListHole

- package.json
- src/components/card/CardHole.jsx
- src/components/card/_card.scss
> Add mintSecondary and lavender colors fo Card component

- package.json
- src/components/action-list/ActionListHole.jsx
- src/components/action-list/ActionListHole.spec.jsx
- src/components/action-list/action-list.scss
- src/components/action-list/pages/action-list.jsx
> Action list hole equal width

- package.json
- src/components/card/CardHole.jsx
- src/components/card/_card.scss
> Add mintSecondaryLight modifier to CardHole

- package.json
- src/components/text/HeaderPrimary.jsx
- src/components/text/HeaderPrimary.spec.jsx
- src/components/text/HeaderSecondary.jsx
- src/components/text/HeaderSecondary.spec.jsx
- src/components/text/_headers.scss
- src/components/text/headerConsts.js
- src/components/text/pages/headers-interactive.jsx
- src/components/text/pages/headers.jsx
> Header Transforms

- package.json
- src/components/rating/Rating.jsx
- src/components/rating/Rating.spec.jsx
- src/components/rating/pages/rating-interactive.jsx
- src/components/rating/pages/rating.jsx
> No label option for rating

- package.json
- src/components/action-list/ActionList.jsx
- src/components/action-list/ActionList.spec.jsx
- src/components/action-list/action-list.scss
- src/components/action-list/pages/action-list.jsx
> Added space-around and space-evenly to action list

- package.json
- src/components/box/Box.jsx
- src/components/box/Box.spec.jsx
- src/components/box/_box.scss
- src/components/box/pages/box.jsx
remove padding-right, make 'x' smaller - design team request :)
Before:
After:
> Change message box

- package.json
- src/components/spinner/Spinner.jsx
- src/components/spinner/Spinner.spec.jsx
- src/components/spinner/_spinner.scss
- src/components/spinner/pages/spinners-interactive.jsx
- src/components/spinner/pages/spinners.jsx
> add spinner sizes and change color

- package.json
- src/components/bubble/Bubble.jsx
- src/components/bubble/Bubble.spec.jsx
- src/components/bubble/_bubble.scss
- src/components/bubble/pages/bubble-interactive.jsx
- src/components/bubble/pages/bubble.jsx
> Add option to Bubble to disable box-shadow

- package.json
- src/components/layout/_layout.scss
- src/components/layout/pages/layout.jsx
> Reverse order layout

- package.json
- src/components/card/Card.jsx
- src/components/card/Card.spec.jsx
- src/components/card/CardHole.jsx
- src/components/card/_card.scss
- src/components/card/pages/card-interactive.jsx
- src/components/card/pages/card.jsx
Needed for https://projects.invisionapp.com/share/38LHAR5TRNY#/screens/304191760
> Vertical card

- package.json
- src/components/list/List.jsx
- src/components/list/List.spec.jsx
- src/components/list/ListItem.jsx
- src/components/list/ListItem.spec.jsx
- src/components/list/ListItemIcon.jsx
- src/components/list/ListItemIcon.spec.jsx
> Add classname support to ListItem && ListItemIcon

- package.json
- src/components/text/TextBit.jsx
Changes:
- there should be an option to use default size in a statement like that 
`condition ? TEXT_BIT_SIZE.SMALL : SIZE.NORMAL`
> BUGFIX - Add NORMAL size for BIT

- package.json
- src/components/text/Headline.jsx
- src/components/text/Headline.spec.jsx
- src/components/text/_headlines.scss
- src/components/text/headlineConsts.js
- src/components/text/pages/headlines-interactive.jsx
- src/components/text/pages/headlines.jsx
We need to support alignment also in Headline. As Headlines would tend to appear in pair with body text we need to have the same options for both components.
Flow would be added later on, as soon as body text implementation is done.
> Alignment in headlines

- package.json
- src/components/content-box/ContentBox.jsx
- src/components/content-box/ContentBox.spec.jsx
- src/components/content-box/ContentBoxActions.jsx
- src/components/content-box/ContentBoxActions.spec.jsx
- src/components/content-box/ContentBoxConstants.jsx
- src/components/content-box/ContentBoxContent.jsx
- src/components/content-box/ContentBoxContent.spec.jsx
- src/components/content-box/ContentBoxHeader.jsx
- src/components/content-box/ContentBoxHeader.spec.jsx
- src/components/content-box/ContentBoxTitle.jsx
- src/components/content-box/ContentBoxTitle.spec.jsx
- src/components/content-box/_content-box.scss
- src/components/content-box/pages/content-box-interactive.jsx
- src/components/content-box/pages/content-box.jsx
I added it so we know that this functionality is needed when designing new system
> Update content box

- package.json
- src/components/text/TextBit.jsx
- src/components/text/_text-bits.scss
- src/components/text/pages/text-bit.jsx
It was requested from design team to add additional colors for BIT texts.
> Adding additional colors to bit

- package.json
- src/components/text/_headlines.scss
Fixes mistake in line-height for xsmall headline
> BUGFIX - update line-height for Headline xsmall

- package.json
- src/components/colors/colors.js
- src/components/colors/hex.spec.js
- src/sass/_config.scss
Changes:
- additional dark color needed for hovers in buttons.
- update values for colors according to new palette
> Update colors to new palette

- package.json
- src/components/box/_box.scss
- src/components/bubble/_bubble.scss
- src/components/icon-as-button/_icon-as-button.scss
- src/components/icons/_icons-mixin.scss
- src/docs/_sass/_docs-active-block.scss
> Remove missing SCSS

- src/components/icon-as-button/_icon-as-button.scss
> Fix navy blue again

- package.json
- src/components/colors/colors.js
- src/sass/_config.scss
> Update palette final version

- package.json
The previous version fails on TC, SG tag is pointing to failing version. This should fix the issue.
> Bugfix - v142.10.1

- package.json
- src/components/flash-messages/FlashMessage.jsx
- src/components/flash-messages/_flash-messages.scss
> Fix colors in flash messages

- package.json
- src/components/form-elements/_text-input.scss
It looks weird specially in placeholders
> remove input text stroke

- package.json
- yarn.lock
flow bump looks like no errors :)
> flow version bump

- .flowconfig
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icon-as-button/IconAsButton.spec.jsx
- src/components/icon-as-button/subcomponents/IconAsButtonContent.jsx
- src/components/icons/Icon.jsx
- src/components/overlayed-box/OverlayedBox.jsx
- src/components/separators/SeparatorHorizontal.jsx
- src/components/separators/SeparatorVertical.jsx
add flow types to separators, icon as button and overlayed box components
> Some more flow types

- package.json
- src/components/form-elements/Checkbox.jsx
- src/components/form-elements/Radio.jsx
- src/docs/components/DocsActiveBlockSettings.jsx
- src/js/generateRandomString.js
- yarn.lock
* write function generateRandomString
> remove node-uuid

- package.json
- src/components/flex/FLEXBOX.md
- src/components/flex/Flex.jsx
- src/components/flex/Flex.spec.jsx
- src/components/flex/FlexConsts.js
- src/components/flex/SPACING.md
- src/components/flex/_flex.scss
- src/components/flex/pages/flex-interactive.jsx
- src/components/flex/pages/flex.jsx
- src/docs/navigation.js
- src/docs/page-components.jsx
- src/sass/main.scss
I know it's big, but it's kinda one thing that I introduce here and big part of it is documentation. So... Flex and it's documentation:
- introduction of Flex component - jsdocs and documentation is included. I added also Markdown docs to have some examples of usage. I added small description in the flex page
- documentation of the spacing was missing for a while so I added also in this PR, as spacings are used in margins setup in the Flex component
> Introduce flexbox component

- package.json
- src/components/content-box/ContentBox.jsx
- src/components/content-box/ContentBoxActions.jsx
- src/components/content-box/ContentBoxConstants.jsx
- src/components/content-box/ContentBoxContent.jsx
- src/components/content-box/ContentBoxHeader.jsx
- src/components/content-box/ContentBoxTitle.jsx
- src/components/flash-messages/FlashMessage.jsx
- src/components/icons/Icon.jsx
flowStrict for
- Icon
- FlashMessage
- ContentBox
- ContentBoxActions,
- ContentBoxContent,
- ContentBoxHeader,
- ContentBoxTitle
> Flow strict for some components

- package.json
- src/components/action-list/ActionList.jsx
- src/components/action-list/ActionListHole.jsx
- src/components/badges/TextBadge.jsx
- src/components/breadcrumbs/Breadcrumb.jsx
- src/components/bubble/Bubble.jsx
- src/components/form-elements/Radio.jsx
- src/components/overlayed-box/OverlayedBox.jsx
- src/components/separators/SeparatorHorizontal.jsx
- src/components/separators/SeparatorVertical.jsx
- src/components/text/Headline.jsx
- src/components/text/TextBit.jsx
- src/components/text/headlineConsts.js
- src/js/generateRandomString.js
these modules was already `flow strict` compatible so no changes were required
> marked all strict-compatible modules as strict

- src/components/math-symbols/MathSymbol.jsx
- src/components/rating/subcomponents/Star.jsx
- src/components/stickers/Sticker.jsx
- src/components/subject-icons/SubjectIcon.jsx
- src/components/subject-icons/SubjectIconBox.jsx
- src/components/toplayer/TopLayer.jsx
some files are already strict, but i forgot to add them in previous PR
> more missing strict files

- .eslintrc
- flow-typed/globals.js
- package.json
- src/docs/components/CodeBlock.jsx
- src/docs/components/DocsActiveBlock.jsx
- src/docs/index.html
- src/docs/layouts/ItemsInteractivePage.jsx
- src/docs/page-components.jsx
- src/docs/pages/interactive.jsx
- src/docs/webpackEntry.jsx
- src/main.scss
- webpack.config.js
- yarn.lock
it currently builds only interactive pages. will add others in separate PR. it should be compatible with current builds and work separately.
> basic webpack build for interactive pages

- .eslintrc
- package.json
- src/docs/index.html
- src/docs/layouts/IndexPage.jsx
- src/docs/layouts/NavigationSPA.jsx
- src/docs/webpackEntry.jsx
- webpack.config.js
- yarn.lock
mostly work for all pages, but some stuff still TBD:
- iframe pages doesn't work
- popup with source code for non-interactive pages
- search in the header
> added webpack dev build for other pages

- package.json
- src/components/rating/Rating.jsx
- src/components/rating/_rating.scss
- src/components/rating/subcomponents/Star.jsx
changes:
1. Use star icon from a new set of icons in Rating component.
2. Update icon size in Rating component.
before:
after:
> Use std-star icon in Rating

- package.json
- src/components/form-elements/Input.jsx
- src/components/search/Search.jsx
Add the ability to add CSS class directly to Search input
https://github.com/brainly/style-guide/issues/1615
> SG-1615 -- inputClass name prop

- package.json
- src/components/box/Box.jsx
- src/components/box/_box.scss
needed in payments (in at least 3 places now)
> add peach secondary box color

- package.json
- src/components/form-elements/Checkbox.jsx
- src/components/form-elements/_checkbox-radio.scss
> Use std-check icon in checkbox

- Dockerfile
- gulpfile.js
- package.json
- scripts/tasks/upload-files.js
due to security reasons we stopped using keys.
> Do not use keys for uploading files

- package.json
- src/components/icons/Icon.jsx
- src/images/icons/influence.svg
> Add influence icon

- package.json
- src/index.js
> Bugfix export of counter

- src/components/counters/Counter.jsx
- src/components/counters/Counter.spec.jsx
- src/components/counters/_counters.scss
- src/components/counters/pages/counters-interactive.jsx
- src/components/counters/pages/counters.jsx
More generic solution for counters.
> Adjust counters

- package.json
- src/components/flex/Flex.jsx
- src/components/flex/FlexConsts.js
- src/components/flex/pages/flex.jsx
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content
> flex component / fix typo `space-evenly`

- package.json
- src/components/header/_header.scss
- src/components/home-button/_home-button.scss
before:
`10px;`
`20px;`
after:
`16px;`
`24px;`
> Adjust home-button placement in header

- src/components/labels/Label.jsx
- src/components/labels/Label.spec.jsx
- src/components/labels/_labels.scss
- src/components/labels/pages/labels-interactive.jsx
- src/components/labels/pages/labels.jsx
- src/docs/navigation.js
- src/docs/page-components.jsx
- src/sass/main.scss
They will replace Badge (currently we use only mustard badge on prod, so this will be quick migration)
> New labels

- package.json
- src/components/labels/Label.jsx
- src/components/labels/_labels.scss
> Update padding for labels with close icon

- src/components/buttons/Button.jsx
- src/components/content-box/ContentBoxConstants.jsx
fixes: https://github.com/brainly/style-guide/issues/1369
> Fix const exports #1369

- src/components/counters/_counters.scss
> Adjust paddings of counter small with icon

- src/components/flash-messages/FlashMessage.jsx
- src/components/header/iframe-pages/small-device.jsx
- src/components/header/pages/header-interactive.jsx
- src/components/header/pages/header.jsx
- src/components/spinner-container/pages/spinner-containers.jsx
Align text to center in ```<FlashMessage />``` when text breaks into more than one line - requested by designers
Before:
After:
> align text to center and fix bugs

- src/components/header/iframe-pages/small-device.jsx
- src/components/header/pages/header-interactive.jsx
- src/components/header/pages/header.jsx
change color to white in search -> it'a a fix to my mistake in https://github.com/brainly/style-guide/pull/1722#pullrequestreview-355865172
Before:
After:
> change color to white in search in header

- package.json
> Fix license

- scripts/tasks/watch-docs-templates.js
- scripts/tasks/watch-sass.js
- src/components/dropdowns/Dropdown.jsx
- src/components/dropdowns/_dropdowns.scss
- src/components/dropdowns/pages/dropdowns.jsx
- src/docs/components/ContrastBox.jsx
- update Dropdown with 2 new props (fullWidth, colorMode)
- fix issue with run-sequence in watch mode
> Dropdown component update

- src/components/home-button/_home-button.scss
in style-guide:
on website:
in style-guide:
on website:
> Adjust sizes of logotypes in HomeButton

- src/components/dropdowns/Dropdown.jsx
- src/components/dropdowns/_dropdowns.scss
https://jira.z-dn.net/browse/ANSPRIO-2856
before:
after:
Maciek N. approves
> Dropdown refactor

- src/components/form-elements/Input.jsx
- src/components/form-elements/Input.spec.jsx
- src/components/form-elements/Textarea.jsx
- src/components/form-elements/Textarea.spec.jsx
- src/components/form-elements/_text-input.scss
- src/components/form-elements/_textarea.scss
- src/components/form-elements/pages/input-interactive.jsx
- src/components/form-elements/pages/input.jsx
- src/components/form-elements/pages/textarea-interactive.jsx
- src/components/form-elements/pages/textarea.jsx
https://jira.z-dn.net/browse/ANSPRIO-2854
> Add error messages for inputs

- src/components/buttons/Button.jsx
- src/components/buttons/README.md
- src/components/buttons/_buttons.scss
- src/components/buttons/pages/buttons.jsx
- src/docs/_sass/_docs-buttons.scss
remove destructive and warning button type (https://jira.z-dn.net/browse/ANSPRIO-2965)
> remove destructive and warning button type

- src/components/flex/_flex.scss
> Prioritize margin props and small

- src/components/buttons/_buttons.scss
https://jira.z-dn.net/browse/ANSPRIO-2966
https://app.abstract.com/projects/faec2e90-f47a-11e8-abea-7339a77b6e7b/branches/master/commits/c5895a2cef7fdc9ab89786260090ff0dbf3e92b4/files/318BAC99-E73C-497D-8CA1-FA96AB613A07/layers/3CBC62C2-1112-41B1-8898-4D522E9F9A43?collectionId=f54fe26e-7d1c-42c7-968b-dd6e7fac3388&collectionLayerId=c6118a33-707b-46b7-80fc-94ab3bb84332&mode=build&selected=3623381849-5DC8131C-C5B1-444D-9894-5769D9891D31
before:
after:
> Change paddings for transparent buttons

- src/components/flex/pages/flex.jsx
Changes only in Flex component documentation
> Use proper size classes in Flex spacing doc

- src/components/action-list/pages/action-list.jsx
- src/components/content-box/pages/content-box.jsx
- src/docs/navigation.js
we should be able to achieve all combinations on layout using `Flex` component
> Mark ContentBox and ActionList as deprecated

- package.json
bump version to v161.6.0
https://github.com/brainly/style-guide/pull/1792
https://github.com/brainly/style-guide/pull/1791
@seahindeniz -fyi I am bumping version with 2 new icons and marked ContentBox and ActionList as deprecated :)
> bump version to v161.6.0

- src/components/form-elements/Input.jsx
- src/components/form-elements/Textarea.jsx
- src/components/form-elements/_text-input.scss
- src/components/form-elements/_textarea.scss
https://brainly.atlassian.net/browse/ANSPRIO-3258
and error type change requested by @ElaKrk
> Fixes for input error messages

- CONTRIBUTING.md
> docs - Define adding icons procces

- package.json
- src/components/counters/_counters.scss
> Adjust text position in counter

- package.json
- src/components/overlay/Overlay.jsx
- src/components/overlay/Overlay.spec.jsx
- src/components/overlay/_overlay.scss
- src/components/overlay/pages/overlay-interactive.jsx
needed in tutoring
as far I know used in payments in brainly
> Overlay add dark color

- package.json
- src/components/box/Box.jsx
- src/components/box/_box.scss
Closes https://github.com/brainly/style-guide/issues/1808
> Add mint-secondary-ultra-light color to Box

- package.json
- src/components/colors/colors.js
- src/components/colors/hex.spec.js
- src/components/colors/pages/colors.jsx
requested by Design System Team.
- primary => core
- secondary => additional
- gray => neutrals
> Update color category names

- package.json
- src/components/form-elements/Radio.jsx
- src/components/form-elements/_checkbox-radio.scss
> Fix size of Radio

- package.json
- src/components/counters/Counter.jsx
- src/components/counters/Counter.spec.jsx
- src/components/counters/_counters.scss
- src/components/counters/pages/counters-interactive.jsx
- src/components/counters/pages/counters.jsx
https://brainly.atlassian.net/browse/ANSPRIO-3362
https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/33523275/FNC#COUNTER
No visual changes
> Rename counter sizes

- src/components/home-button/HomeButton.jsx
Current component doesn't implement alt tag for images, we need them to meet SEO requirements on shell app and to be consistent with current version of HTML markup on production site.
> add alt tag for images in HomeButton.jsx component

- package.json
- src/components/form-elements/Select.jsx
- src/components/form-elements/_select.scss
- src/components/form-elements/_text-input.scss
- src/components/form-elements/pages/select-interactive.jsx
- src/components/form-elements/pages/select.jsx
- src/sass/_config.scss
No visual changes
Text input will be done separately
https://brainly.atlassian.net/browse/ANSPRIO-3367
https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/33523275/FNC#SELECT
> Rename Select sizes

- package.json
- src/components/form-elements/Input.jsx
- src/components/form-elements/Input.spec.jsx
- src/components/form-elements/_text-input.scss
- src/components/form-elements/pages/input-interactive.jsx
- src/components/form-elements/pages/input.jsx
- src/components/search/Search.jsx
- src/components/search/Search.spec.jsx
- src/components/search/_search.scss
- src/components/search/pages/search-interactive.jsx
- src/components/search/pages/search.jsx
https://brainly.atlassian.net/browse/ANSPRIO-3364
https://brainly.atlassian.net/browse/ANSPRIO-3366
No visual changes
> Rename Input and Search sizes

- src/components/form-elements/pages/radio.jsx
- src/components/labels/_labels.scss
- src/components/labels/pages/labels.jsx
- src/components/rating/Rating.jsx
- src/components/rating/Rating.spec.jsx
- src/components/rating/_rating.scss
- src/components/rating/pages/rating.jsx
https://brainly.atlassian.net/browse/ANSPRIO-3368
https://brainly.atlassian.net/browse/ANSPRIO-3371
> Rename Rating and Label sizes

- src/components/colors/colors.js
- src/sass/_config.scss
requested by Design System Team
> Add Gray Light 400 to neutral colors

- package.json
> Bump SG to v170.2.0

- package.json
- src/components/buttons/Button.jsx
- src/components/buttons/Button.spec.jsx
- src/components/buttons/_buttons.scss
- src/components/buttons/pages/buttons.jsx
- src/components/search/Search.jsx
> Rename Button sizes

- src/components/avatar/Avatar.jsx
In one of avatar cases, title prop was not passed to div - this minor update fixes it
> Avatar update - pass "title" prop

- src/components/file-handler/FileHandler.jsx
- src/components/file-handler/FileHandler.spec.jsx
Fix file handler type and onClick in FileHandler
We want to pass onClick only for images
> Fix file handler type and onClick in FileHandler

- src/components/buttons/Button.jsx
- src/components/buttons/Button.spec.jsx
- src/components/buttons/_buttons.scss
- src/components/buttons/pages/buttons.jsx
> Add possibility to display button icon on the right

- src/components/file-handler/pages/file-handlers.jsx
https://brainly.atlassian.net/browse/ANSPRIO-3519
> FileHandler / rename types

- src/components/box/Box.jsx
it will help refactor LayoutBox in main app
> Export BoxPropsType from Box

- src/components/file-handler/FileHandler.jsx
- src/components/file-handler/FileHandler.spec.jsx
As requested on design catch up meeting
> Change color mono to white in FileHandler

- src/components/labels/Label.jsx
- src/components/labels/pages/labels.jsx
Remove 'mono' and replace it with 'default' (no color).
Hide unnecessary columns with labels
> Labels colors fix

- src/components/buttons/pages/buttons-interactive.jsx
https://github.com/brainly/style-guide/issues/1899
> Interactive / Add reversedOrder Button prop

- yarn.lock
I upgraded all @babel packages
> Update yarn.lock to support newest node version

- src/components/form-elements/Input.jsx
> Add useRef type to input's setInputRef prop type.

- src/components/text/Link.jsx
- src/components/text/Text.jsx
- src/components/text/_text.scss
- src/components/text/pages/text.jsx
- src/components/text/textConsts.js
Add xxx large size to the body text. This is complementary to the xxx large size for headlines
> Add xxx large to the text

- src/components/avatar/Avatar.jsx
- src/components/avatar/_avatar.scss
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icon-as-button/IconAsButton.spec.jsx
- src/components/icon-as-button/_icon-as-button.scss
- src/components/icon-as-button/pages/icon-as-button.jsx
- src/components/icons/Icon.jsx
- src/components/icons/_icons.scss
- src/components/labels-deprecated/LabelDeprecated.jsx
- src/components/search/Search.jsx
- src/components/search/Search.spec.jsx
https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/33523275/FNC
> Reduce Number of Icon Sizes - Icon, Avatar, IconAsButton and Search

- src/components/box/Box.jsx
- src/components/file-handler/FileHandler.jsx
- src/components/layout/Layout.jsx
closes https://github.com/brainly/style-guide/issues/1869
closes https://github.com/brainly/style-guide/issues/1886
closes https://github.com/brainly/style-guide/issues/1872
thanks @seahindeniz for reporting these issues
> Tiny fixes of Layout, Box and FileHandler 

- src/docs/_sass/_docs-active-block.scss
- src/docs/components/DocsActiveBlock.jsx
- src/docs/navigation.js
- src/docs/pages/interactive.jsx
- src/docs/pages/utilities.jsx
- src/docs/webpackEntry.jsx
- src/sass/pages/utils/introduction.jsx
- src/sass/pages/utils/space-between.jsx
New section in style guide covering utility classes and first section related to **space between** utility.
> Documentation section for utility classes

- src/components/avatar/Avatar.jsx
- src/components/avatar/Avatar.spec.jsx
- src/components/avatar/_avatar.scss
> Fit icon in avatar to occupy full space (and no more)

- src/components/buttons/pages/buttons.jsx
> Add dark background and fix table alignment on buttons presentation

- src/components/accordion/_accordion.scss
I missed one animatable property, sorry, this change will go with `182.1.0`
> Add missing animatable property

- src/components/accordion/AccordionItem.jsx
Add padding prop to AccordionItem
> Add padding prop to AccordionItem

- src/components/icons/Icon.jsx
- src/images/icons/bullet.svg
Add bullet icon to web icons set:
> Add bullet icon

- src/components/accordion/Accordion.jsx
- src/components/accordion/AccordionItem.jsx
Fix weird scroll behavior after expanding the Accordion item.
> Fix issue with scrolling after opening Accordion item

- src/components/accordion/Accordion.spec.jsx
- src/components/box/Box.jsx
- src/components/flex/Flex.jsx
- src/components/utils.js
Without `forwardRef` we are not able to use `ref` on those elements
> Add forwardRef to Box and Flex

- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
- src/components/utils/useReducedMotion.js
> Make it possible to disable animations in accordion - a11y fix

- src/css/config/index.js
Enable motion safe variants for animation related utility classes
> Enable motion safe variants for animation related utility classes

- src/components/counters/Counters.stories.jsx
Add Counter component to Storybook
> Add Counter component to Storybook

- src/components/list/List.stories.jsx
- src/components/list/MenuList.stories.jsx
- add list and menu list to Storybook
I split list into 2 menu items as I think it makes more sense (they are separate components)
> Add Lists to Storybook

- src/components/breadcrumbs/Breadcrumbs.stories.jsx
Add Breadcrumbs component to Storybook
> Add Breadcrumbs component to Storybook

- src/components/accordion/Accordion.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
- src/components/accordion/pages/accordion-interactive.jsx
- src/components/accordion/pages/accordion.jsx
Add reduceMotion prop to Accordion: make it possible to decide when to enable reduce motion. 
https://brainly.atlassian.net/browse/DS-1418
> Add reduceMotion prop to Accordion

- src/sass/_utils.scss
Add 2 classes for fade-in animation, widely used in brainly-frontend app.
> Add utility classes for fade-in animation

- src/docs/navigation.js
- src/sass/pages/utils/animations.jsx
> Update docs with information about new animation classes

- src/components/box/Box.jsx
- src/components/box/_box.scss
> Add additional color to Box

- src/components/spinner/Spinner.jsx
- src/components/spinner/Spinner.spec.jsx
- src/components/spinner/Spinner.stories.jsx
- src/components/spinner/_spinner.scss
- src/components/spinner/pages/spinners-interactive.jsx
- src/components/spinner/pages/spinners.jsx
- removes wrong size (`xsmall` - 20px)
- changes values of `small` and `xsmall`
- introduces new colors
This is enabler before implementing `loading` state in button.
> Change sizes and colors of spinner

- src/components/icons/Icon.jsx
- src/images/icons/shield.svg
> Add shield icon to web package

- .gitignore
- gulpfile.js
- package.json
- scripts/tasks/clean-assets.js
- scripts/tasks/copy-assets.js
> Expose assets folder with images and fonts available from NPM

- gulpfile.js
- scripts/tasks/sass-build.js
> Expose built styleguide.css in npm css folder

- src/docs/navigation.js
- src/sass/_utils.scss
- src/sass/pages/utils/cursor.jsx
https://github.com/brainly/style-guide/issues/2087
> Add cursor: pointer class

- src/components/text/TextBit.jsx
- src/components/text/TextBit.stories.jsx
- src/components/text/_text-bits.scss
- src/components/text/pages/text-bit-interactive.jsx
Changes:
- added support for new value of prop 'type': span
- added new prop 'inherited' - it controls whether nested Textbit should inherit styles
> allow nested textbit to inherit styles

- src/docs/components/JSXGenerator.js
- read JSX tag name from component displayName
Fixes #2080
> display proper JSX in docs

- src/components/icons/Icon.jsx
- src/components/icons/_icons-mixin.scss
> add peach-dark icon color

- src/components/counters/Counters.stories.jsx
Counter component stories updated based on the [figma template](https://www.figma.com/file/Bv6y1xUSN3K89lOyppeYnX/%5BDS%5D-Counter?node-id=716%3A410)
Preview:
> Counter component

- src/components/flash-messages/FlashMessage.stories.jsx
update stories based on figma templates
> update flash message stories

- src/_docs/styles.scss
- src/components/labels/Label.stories.jsx
'types' story
part of it on screenshot below
'trimmed text' story
> align Label stories to figma templates

- scripts/build-types.js
> partial revert of d6ebee2656029b0eb258e70b1790182cbd0a9b8b

- src/index.js
This reverts commit d6ebee2656029b0eb258e70b1790182cbd0a9b8b.
> Revert "improve typings (#2125)"

- package.json
v198.2.0 (2 Nov 2021)
Features:
- Update icons contribution docs
- Update elevation shadows tokens, utilities and docs
- Change opacity to for dark overlay to match guidelines in dialog component
- Use new shadows in components, create shadows documentation in Storybook
- Adjust Transitions of Dialog Component
- Dialog Component - Respect System Reduced Motion
- Fix JSX code snippets for Flex and Box
- Update styles in FileHandler
> Update to v198.2.0

- src/components/dialog/Dialog.jsx
- src/components/dialog/Dialog.stories.jsx
- src/components/dialog/DialogCloseButton.jsx
- src/components/dialog/DialogHeader.jsx
- src/components/dialog/useFocusTrap.js
- aria-* attributes for `Dialog` & `DialogCloseButton`
- focus dialog when there are no focusable descendants
> Dialog a11 improvements

- CONTRIBUTING.md
Update release notes section describing rules for title and headlines within release notes.
> Update release notes section

- src/components/dialog/Dialog.jsx
- src/components/dialog/Dialog.spec.jsx
[Features]
- add additional zIndex prop in order to avoid problems with stacking:
https://user-images.githubusercontent.com/14280367/141443102-c5062973-f8f3-4764-bb32-72c311a87680.mov
> Add additional zIndex property to Dialog

- .github/workflows/integrate.yml
- src/components/buttons/_buttons.scss
> Update chromatic config

- src/components/accordion/Accordion.spec.jsx
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icons/Icon.jsx
- src/components/icons/_icons-mixin.scss
- src/components/icons/_icons.scss
This reverts commit 44bd7b85ee0e73cbb632ad4f82b1845574765fba.
> Revert "Improve `Icon` accessibility (#2188)"

- buildspec-branches.yml
I used wrong script for storybook branch publish and it started failing
> use static build for publish branch storybook

- src/sass/pages/utils/uxmotion.jsx
https://brainly.atlassian.net/browse/DS-2802
> Fix UX motion docs

- scripts/tasks/build-react-interactive-pages.js
replace process.env.STORYBOOK_ENV with webpack
> fix interactive docs crash

- src/components/accordion/Accordion.a11y.spec.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/_buttons.scss
- src/components/form-elements/_checkbox-radio.scss
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icon-as-button/_icon-as-button.scss
- src/components/icons/Icon.jsx
- src/components/icons/_icons-mixin.scss
- src/components/icons/_icons.scss
- src/components/math-symbols/MathSymbol.jsx
- src/components/math-symbols/_math-symbol-icon.scss
- src/components/mobile-icons/_mobile-icon.scss
- src/components/rating/_rating.scss
- src/components/search/_search.scss
- src/components/subject-icons/SubjectIcon.jsx
- src/components/subject-icons/_subject-icon.scss
This reverts commit f1ecdbec7d4c8d5d83eb3330d15bc07683cebc7f.
> Revert "A11y improvements icon (#2209)"

- src/components/accordion/Accordion.a11y.spec.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/_buttons.scss
- src/components/form-elements/_checkbox-radio.scss
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icon-as-button/_icon-as-button.scss
- src/components/icons/Icon.jsx
- src/components/icons/_icons-mixin.scss
- src/components/icons/_icons.scss
- src/components/math-symbols/MathSymbol.jsx
- src/components/math-symbols/_math-symbol-icon.scss
- src/components/mobile-icons/_mobile-icon.scss
- src/components/rating/_rating.scss
- src/components/search/_search.scss
- src/components/subject-icons/SubjectIcon.jsx
- src/components/subject-icons/_subject-icon.scss
Co-authored-by: katarzynatobis <60467496+katarzynatobis@users.noreply.github.com>
> Reapply of A11y improvements icon (#2209)

- scripts/build-styleguide-s3.js
if stylesheet is not found then build
> DS-3115 handle not found error

- src/components/buttons/Button.stories.jsx
> Fix button story to properly show icon

- src/components/dialog/Dialog.jsx
It fixes an error while building the server-side Next.js application.
> Dialog - Fix Undefined Window in Server-Side Rendering

- scripts/build-storybook-s3.js
- scripts/build-styleguide-s3.js
> fix deploy version check path

- src/components/file-handler/FileHandler.jsx
- src/components/text/Link.jsx
- onClick added to Link as "a"
- fixed onClick type
> Link fixes

- src/components/dialog/Dialog.stories.jsx
https://user-images.githubusercontent.com/1231144/157022558-1202761a-46bb-41af-9e96-e03ece0e2965.mov
https://user-images.githubusercontent.com/1231144/157022603-1fc2b6ee-dd73-4880-8be3-219e81c9686c.mov
> Dialog - Fix story after a11y Link changes

- scripts/build-styleguide-s3.js
New terraform deploy is uploading styleguide docs do `dev` directory. There is missing `--production` flag on script
> change tf deploy directory

- package.json
- src/components/dialog/Dialog.jsx
- src/components/dialog/_dialog.scss
- src/sass/_config.scss
- Adjusted Dialog fullscreen animation per Giga's request
- Fixed Dialog controls display in the storybook
> Adjust Dialog fullscreen animation; fix Dialog controls display in storybook

- src/components/flex/Flex.jsx
- src/components/flex/Flex.spec.jsx
- src/components/flex/FlexConsts.js
- src/components/flex/_flex.scss
- src/sass/_config.scss
Flex component:
- `none` value added to margin, marginTop, marginBottom, marginLeft, marginRight props
> add none to Flex margin props values

- scripts/build-styleguide-s3.js
This should fix false negative message codebuild fail. It happens when we skip build if styleguide version has not changed
> make empty dir if version has not changed

- src/_docs/stories/responsive-props.stories.mdx
- src/components/text/Headline.chromatic.stories.jsx
- src/components/text/Headline.stories.mdx
New responsive props section is added to Headline component storybook Docs tab
> add documentation for responsive props of Headline component

- src/components/buttons/_buttons.scss
Outline inverted button should not have background
> remove outline inverted button background

- src/components/transition/Transition.jsx
to reuse an existing custom hook from utils
> Transition Component - Use Reduced Motion Hook

- src/components/avatar/stories/Avatar.a11y.mdx
- src/components/counters/Counter.a11y.spec.jsx
- src/components/counters/Counter.jsx
- src/components/counters/Counters.stories.mdx
- src/components/counters/_counters.scss
- src/components/counters/stories/Counter.a11y.mdx
- src/components/dialog/stories/Dialog.a11y.mdx
- a11y documentation
- a11y tests
- new prop `aria-label` for the Counter
> Counter accessiblity improvements

- scripts/build-storybook-s3.js
This should fix dev deploy to new bucket.
> fix storybook dev deploy

- gulpfile.js
- scripts/tasks/fingerprint-replace-new.js
I'm adding modified `fingerprint-replace` task as `fingerprint-replace-new` for new build.
> add new task for fingerprint replace

- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
- improved transitions in AccordionItem: durations and easings from UX Motion variables
- reduced transition for reduceMotion option (as a prop and as a system setting): all transitions have been removed
ProtoPie: https://cloud.protopie.io/p/13b6b9951f https://cloud.protopie.io/p/13b6b9951f/r/5b5450fe
https://user-images.githubusercontent.com/60467496/173898541-be51292e-6ae4-4307-ab28-b421e174d89d.mov
> Transitions improvements for Accordion

- .storybook/public/manager.css
> Change side item radius to mimic brainly tab

- src/components/dialog/Dialog.jsx
- src/components/dialog/DialogCloseButton.jsx
- add `aria-description` to Dialog
- add `disabled` to DialogCloseButton
closes #2367
> Add aria-description to Dialog and disabled to DialogCloseButton

- package.json
- new colors for Label component #2464
- removed the old color palette, CSS and SASS color variables generated during the build process from `src/components/colors/colors.js`#2469 
- accessibility improvement for Label component #2457 
- new icons `caret_down` & `caret_up` #2472 
- `aria-description` to Dialog and `disabled `to DialogCloseButton added #2467 
- new component SkipLink #2408 (with working chromatic story #2460)
- fixed outside scroll placing in Dialog #2468 
- fixed relative parent for Link as="button" #2470
- Transition Component - Fire Callbacks After Instant Animation #2463 
- responsive introduction page header #2465 
- <mark> replaced with InfoBox component in mdx  #2466
- Change side item radius to mimic Brainly tab #2461 
- align storybook UI with brainly design …
> Bump version to 216.0.0

- package.json
- new mobile icons #2474
- fix unwanted deploys #2480
> Bump version to v216.0.2

- scripts/build-s3.js
AccessDenied does not guarantee that file does not exist but we have to rely on it and build files and continue deploy
> build files if AccessDenied

- src/components/form-elements/Select.jsx
- src/components/form-elements/_select.scss
- src/sass/_config.scss
- change icon from arrow_down to caret_down
- add size s to select
-
> Select - add size S, replace arrow_down icon with caret_down

- src/components/form-elements/checkbox/Checkbox.jsx
- src/components/form-elements/checkbox/Checkbox.stories.mdx
- src/components/form-elements/checkbox/_checkbox.scss
- src/components/form-elements/radio/Radio.jsx
- src/components/form-elements/radio/Radio.stories.mdx
- src/components/form-elements/radio/_radio.scss
- added small label size
- fixed invalid state appearance on Radio circle
- fixed Radio circle position
- add asterisk to label when Checkbox is required
> Checkbox & Radio improvements

- src/docs/stories/introduction.stories.mdx
> Fix documentation with links to external js containing icons

- package.json
- rename `iconHidden` prop to `iconAriaHidden` in Label #2509 
- accessibility improvements for the Button #2506 
- redirect to store when no version is in url #2514 
- Fix documentation with links to external js containing icons #2517
> bump to v219.0.0

- .storybook/preview.js
- src/components/utils/useReducedMotion.stories.mdx
> Move public hooks to the new category in storybook

- src/docs/stories/introduction.stories.mdx
> Add link to the pencil design system in the docs

- .storybook/main.js
> improve storybook error message

- src/components/dialog/Dialog.jsx
- src/components/transition/Transition.jsx
> Fix Dialog and Transition not to break SSR

- scripts/build-s3.js
> fix .temp file path on prod deploy

- src/components/form-elements/radio/RadioGroup.jsx
- src/components/form-elements/radio/useRadioContext.jsx
The change results in proper typescript declaration
> Expose proper onChange event type in radio group

- src/components/form-elements/checkbox/Checkbox.jsx
- src/components/form-elements/checkbox/Checkbox.stories.mdx
This change fixes unnecessary animation on multiple checkboxes.
Fixes #2601
> fix Checkbox unnecessary render

- src/docs/stories/shadows.stories.mdx
- src/docs/stories/utilities/shadows.stories.mdx
> fix shadows invisible on storybook

- package.json
- scale up hover effect & press feedback buttons (https://github.com/brainly/style-guide/pull/2636)
https://github.com/brainly/style-guide/labels/Change%3A%20Visual
- Rewrite tests with react testing library (https://github.com/brainly/style-guide/pull/2669)
> bump version to 223.1.0

- .eslintrc.rules.js
- src/components/sparks/Particle.tsx
- src/components/sparks/Sparks.spec.tsx
- src/components/sparks/Sparks.stories.mdx
- src/components/sparks/Sparks.tsx
- src/components/sparks/_sparks.scss
- src/components/sparks/animation.ts
- src/components/sparks/presets.ts
- src/components/sparks/stories/Sparks.a11y.mdx
- src/components/sparks/stories/rules.a11y.ts
- src/components/sparks/timeout.ts
- src/index.ts
- tsconfig.json
https://user-images.githubusercontent.com/8572321/220912887-a21dfaaa-2c62-4b03-95f0-98720ebce158.mp4
https://user-images.githubusercontent.com/8572321/220912907-e1306516-96fe-44aa-a01e-1e6872866c48.mp4
https://user-images.githubusercontent.com/8572321/220912916-931653f0-3774-499f-b47e-e7a8b5c1e3d2.mp4
> Sparks component ✨

- src/components/sparks/Sparks.chromatic.stories.tsx
- src/components/sparks/animation.ts
Should be like that in chromatic.
> Add animation debug mode for visual testing

- package.json
- patches/@storybook+react+6.5.13.patch
- yarn.lock
This fixes docs code snippets. They don't contain `MDXCreateElement` anymore
> patch @storybook/react to fix polluted code snippets

- .github/workflows/integrate.yml
Trigger build, test and chromatic:
- on all pull requests
- after merge to master
> Trigger gh actions on all pull requests and only after merge to master

- src/components/search/Search.tsx
- src/components/search/_search.scss
> Fix #2713 - search unmounts unexpectedly

- src/components/search/Search.tsx
> Add button type to Search

- package.json
- Add button type to Search #2733
> Bump version to v224.4.0

- .storybook/preview.js
> Fix source code of stories with custom decorators 

- src/components/form-elements/radio/Radio.tsx
- src/components/form-elements/radio/_radio.scss
> Add white circle to the checked Radio

- src/docs/stories/focus.stories.mdx
- src/sass/_basics.scss
- src/sass/_focus.scss
Parameterise focus width to customise the effect.
> Parametrise focus widths

- src/components/chip/Chip.tsx
- src/components/chip/_chip.scss
Closes #2749
After:
https://github.com/brainly/style-guide/assets/8572321/53ff2ae7-45f1-4fe1-9f01-7dd7c051234e
> Improve click experience of chip for iOS

- src/components/card-interactive/_card.scss
Fixing leftover after changing component layout.
> Remove tap highlight on iOS

- src/components/select-menu/SelectMenu.spec.tsx
- src/components/select-menu/useFloatingSelectMenu.tsx
Fixes: https://brainly.atlassian.net/browse/BIC-99
> fix selectmenu reopen on mobile

- src/index.ts
Export ButtonLite from components
> export ButtonLite from SG

- package.json
Release v227.0.0 introducing React 18
> Release v227.0.0

- package.json
> chore: 🔖 release v227.2.0

- package.json
> chore: 🔖 release v227.3.0

- package.json
> chore: 🔖 release v227.3.1
