- src/components/form-elements/_form-elements.scss
closes https://github.com/brainly/style-guide/issues/206
before
after
> Removed shadow on textarea on iOS

- Dockerfile
... so that we do not download and build docsets during image creation
> Added parameters to skip rdoc installation for ruby gems in Dockerfile

- scripts/cibuild.sh
- scripts/server.sh
It will help to get rid of possible issues with stale docker images with backed-in package.json containing old version
> Added package.json mounting

- src/components/box/_box.scss
- src/components/box/box.html
- src/docs/_data/navigation.yml
- src/docs/_sass/_docs-block.scss
- src/sass/main.scss
As you can see in the "example usage" the spacing is wrong, but that's an issue of content-box (we have a separate ticket for that).
> Add new component  - mint-box . Closes #181

- src/components/form-elements/_form-elements.scss
- src/components/form-elements/form-elements.html
- src/components/search/_search.scss
- src/components/search/search.html
Closes #247
To recreate search from http://brainly.com/ I had to add two new modifiers to `mint-input`: mint-input--large and mint-input--subtle-border: 
"Hero search" looks like this on desktop:
And like this on mobile:
> Add hero search 

- src/components/dropdowns/_dropdowns.scss
- src/components/dropdowns/dropdowns.html
- src/components/labels/_labels.scss
closes https://github.com/brainly/style-guide/issues/272
below you can see behaviour when dropdown's width is limited.
> Added --full-width modifiers to labels and added fix for dropdowns

- src/components/form-elements/_form-elements.scss
- src/components/form-elements/form-elements.html
closes https://github.com/brainly/style-guide/issues/274
this small one is gonna be used instead of dropdown in the filters on small screens.
> Added --small select

- src/components/dropdowns/_dropdowns.scss
- src/components/dropdowns/dropdowns.html
closes https://github.com/brainly/style-guide/issues/281
its size is the same like small select:
> Fixed behaviour of dropdowns

- src/components/form-elements/_form-elements.scss
(default form elements don't have that). Fixes issue with Opera Mini. Closes #246
> Remove cursor:pointer from form elements 

- gulpfile.js
- scripts/watch.sh
- src/docs/_config.yml
- src/docs/_layouts/default.html
- src/docs/_sass/main.scss
Jekyll has a build-in SCSS compiler, it worked fine but wasn't flexible enough for our needs (no autoprefixer). We decided to reuse the same workflow that we use for building style guide SCSS.
Fixes #287
> Build SCSS using gulp instead of jekyll

- src/components/footer/_footer.scss
- src/components/form-elements/_form-elements.scss
- src/components/header/_header.scss
- src/components/list/_list.scss
- src/docs/_sass/_color-box.scss
- src/docs/_sass/_docs-block.scss
- src/docs/_sass/main.scss
- src/sass/_basics.scss
- src/sass/_mixins.scss
Added border-box globally, removed it from components.
Only thing that broke are iframes in the styleguide, but I replaced default iframe border with a shadow:
> Make box-sizing:border-box global. Fixes #260

- package.json
- src/components/content-box/_content-box.scss
- src/components/footer/_footer.scss
- src/components/footer/footer.html
- src/components/form-elements/_form-elements.scss
- src/components/header/_header.scss
- src/components/header/header.html
- src/components/home-button/_home-button.scss
- src/components/logo/_logo.scss
- src/components/text/_text.scss
- src/components/toplayer/_toplayer.scss
- src/sass/_config.scss
- src/sass/_helpers.scss
This is breaking change.
Update:
mint-hide-for-desktop => mint-hide-for-medium-up
mint-hide-for-mobile => mint-hide-for-small-only
$breakpointTablet => $breakpointMedium
$breakpointDesktop => $breakpointLarge
> Fix mint-hide-for-desktop class

- src/components/labels/_labels.scss
- src/components/labels/labels.html
closes https://github.com/brainly/style-guide/issues/180
> Added --large modifier for label

- gulpfile.js
It was bothering me for a while - why we had ie8/9 support there? I'm not 100% about these new settings, just wanted to open a quick discussion.
> Change browser support to the last two versions + opera mini.

- src/components/text/_text.scss
- src/components/text/text.html
> Add warning and error text options

- src/components/badges/_badges.scss
- src/components/form-elements/select.html
- src/components/labels/_labels.scss
- src/components/rating/_rating.scss
- src/components/separators/_horizontal-separator.scss
- src/components/separators/_separators.scss
- src/sass/_mixins.scss
closes #383
closes #354
Small labels, small rating box and badge can't have min-height of vertical rhythm as they not fit buttons.
For now min-height is disabled for those small elements.
We can keep it that way and add some modifier to use those elements as standalone components (with margin compensation for it). We can make this min-height: 0 as some modifier and apply it when used in buttons etc. Maybe other ideas?
@mr-mig @kdzwinel @vergilius @matzimowski
> Fix issue in safari rating/badges/labels

- s3_website.yml
I've added new definitions for gzip.
After PR is merged I will deploy the `prerelease` version **manually** to forcibly oveeride the files on s3.
**It will affect the old js-icons/svgs**. Those files should be served gzipped for v20.
> Added js + svg + font to s3_website gzip definition

- src/components/icons/_icons.scss
- src/components/icons/icons.html
- src/docs/_data/icons.yml
- src/docs/_sass/main.scss
closes https://github.com/brainly/style-guide/issues/484
> Add missing icon size

- src/components/labels/_labels.scss
- src/components/rating/_rating.scss
- src/sass/_fixes.scss
- src/sass/_mixins.scss
- src/sass/main.scss
Fixed #482 
Fixed #489 
Labels::
Buttons with labels:
> Added opera mini fix for label font

- src/components/header/header.html
- src/components/overlayed-box/_overlayed_box.scss
- src/components/overlayed-box/overlayed-box.html
Closes https://github.com/brainly/style-guide/issues/485
This is a breaking change -> requires updating of html structure.
Was:
```
<div class="mint-overlayed-box">
<button class="mint-icon-as-button">
<div class="mint-icon-as-button__hole">
<svg class="mint-icon mint-icon--x26 mint-icon--adaptive">
<use xlink:href="#icon-messages"></use>
</svg>
</div>
</button>
<div class="mint-overlayed-box__overlay">
<div class="mint-badge mint-badge--error">1</div>
</div>
</div>
```
Is:
```
<button class="mint-icon-as-button mint-icon-as-button--light">
<div class="mint-icon-as-button__hole">
<div class="mint-overlayed-box">
<svg class="mint-icon mint-icon--x26 mint-icon--adaptive">
<use xlink:href="#icon-profile"></use>
</svg>
<div class="mint-overlayed-box__overlay">
<div class="mint-badge …
```
> Update overlayed box

- src/components/breadcrumbs/_breadcrumbs.scss
- src/components/breadcrumbs/breadcrumbs.html
Fixes #417 
The size of these breadcrumbs vertically is smaller, then the default one - it can be incorporated in text... (though, not visible on a screenshot)
> Added --short modifier for breadcrumbs

- src/components/labels/_labels.scss
- src/components/rating/_rating.scss
- src/components/text/_headers.scss
closes https://github.com/brainly/style-guide/issues/572
closes https://github.com/brainly/style-guide/issues/574
before:
after:
before:
after:
before:
after:
Before:
After:
Select to compare with:
> Update font family for labels, rating and primary headers

- src/components/text/_text.scss
- src/components/text/text.html
closes https://github.com/brainly/style-guide/issues/442
> Update mint-text add 'small' option

- src/components/form-elements/_select.scss
closes https://github.com/brainly/style-guide/issues/579
Before:
After:
> Fix selects sizes

- src/components/buttons/buttons.html
- src/components/labels/_labels.scss
- src/components/labels/labels.html
closes https://github.com/brainly/style-guide/issues/589
closes https://github.com/brainly/style-guide/issues/588
Before:
After:
> Fix characters cut on labels

- src/components/helpers/rwd.html
- src/docs/_data/navigation.yml
:two_hearts: show up and hide when you resize the page
> Expose mint-hide-for-* helper classes in the docs

- src/components/form-elements/_text-input.scss
> Fix for mint-input--large placeholder

- src/components/form-elements/_textarea.scss
Placeholder styles should match those of input text
> Update textarea placeholder styles

- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
closes https://github.com/brainly/style-guide/issues/470
> Add icon as button dark option

- gulpfile.js
- package.json
- scripts/tasks/root-redirect-page.js
- src/root-redirect.html
using simple, yet effective, html meta redirect
http://styleguide.brainly.com/ will finally redirect to the latest version of the doc automagically ✨
✴it won't work locally as local root (/dist/version/docs) is different from the production root (/version/docs)
> Redirect from root folder to the latest styleguide version docs 

- src/components/progressbar/_progressbar.scss
> Updated look of progress-bar

- package.json
- src/components/box/_box.scss
- src/components/box/box.html
closes https://github.com/brainly/style-guide/issues/612
closes https://github.com/brainly/style-guide/issues/700
we have decided no to add `--with-pattern` to style-guide
> Improved mint box

- package.json
- src/components/labels/_labels.scss
closes https://github.com/brainly/style-guide/issues/629
> Fix mint-label__icon

- package.json
- src/components/icons/_icons.scss
- src/docs/_data/icons.yml
closes https://github.com/brainly/style-guide/issues/720
> Add mint color of icons

- package.json
- src/components/text/_text.scss
- src/components/text/text.html
closes https://github.com/brainly/style-guide/issues/706
it looks differently on different backgrounds.
it's already in use in game-box and baby-progress-bar features.
example (baby progress bar):
> Add dark-semitransparent text

- package.json
- src/components/buttons/_buttons_secondary.scss
closes https://github.com/brainly/style-guide/issues/664
before:
after:
> Add white-space: nowrap to hole of button-secondary

- package.json
- src/components/content-box/_content-box.scss
- src/components/content-box/content-box.html
closes https://github.com/brainly/style-guide/issues/600
> Add --with-centered-text modifier to mint-content-box__content

- package.json
- src/components/box/_box.scss
- src/components/buttons/_buttons_secondary.scss
Fix box borderSize variable
Before:
After:
> Fix secondary buttons small line height in safari

- package.json
- src/components/toplayer/_toplayer.scss
- src/components/toplayer/default_toplayer.html
- src/components/toplayer/notlogged_toplayer.html
- src/components/toplayer/toplayer.html
- src/docs/_sass/_docs-block.scss
closes https://github.com/brainly/style-guide/issues/377
we already do not use this containers.
there is only one case of usage in `symfony` that will be refactored when version of style-guide is bumped
it's major change, right?
> Clean toplayer component up

- package.json
- src/components/box/_box.scss
closes https://github.com/brainly/style-guide/issues/766
white background is default now.
> Add sg-box light modifier

- package.json
- src/components/form-elements/_select.scss
- src/components/form-elements/select.html
before:
after:
- removed `--small` modifier
- added `--valid` modifier
> Update select component

- package.json
- src/components/avatar/_avatar.scss
- src/components/avatar/avatar.html
- src/docs/_sass/_docs-block.scss
closes https://github.com/brainly/style-guide/issues/815
fixes issue with weird spacing around avatars
> Update sg-avatar to be display block

- package.json
- src/components/buttons/_buttons_secondary.scss
when hovered (same as the rest of buttons)
> Set transparent background for sg-button-secondary--inverse

- package.json
- src/components/icons/_icons.scss
- src/docs/_data/icons.yml
closes https://github.com/brainly/style-guide/issues/825
> Add gray-light modfier for icon

- package.json
- src/components/form-elements/_textarea.scss
- src/components/form-elements/textarea.html
closes https://github.com/brainly/style-guide/issues/861
> Add simple modifier for textarea

- package.json
- src/components/badges/_badges.scss
- src/components/badges/badges.html
closes https://github.com/brainly/style-guide/issues/801
> Add modifiers for badge

- .gitignore
- gulpfile.js
- package.json
- scripts/tasks/build-copy-package-json.js
Version number is back!
closes https://github.com/brainly/style-guide/issues/882
> Fix style guide display issue

- package.json
- src/components/form-elements/_textarea.scss
- src/components/form-elements/textarea.html
closes https://github.com/brainly/style-guide/issues/893
renamed from `--wrapper` to `--auto-height`
usage:
> Add auto-height modifier to textarea

- src/components/header/header.html
- src/components/header/small-device.html
- src/components/search/search.html
> Fix for search-light placeholder on mobile

- package.json
- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
closes https://github.com/brainly/style-guide/issues/833
currently used in challenges (status === falied)
after:
before:
> Add peach modifier to icon-as-button

- package.json
- src/components/content-box/_content-box.scss
Unwanted spacing in attachments because `--spaced` styles are cascading
> Content box spaced - do not apply to children

- package.json
- src/components/buttons/_icon-as-button.scss
- src/components/buttons/icon-as-button.html
closes https://github.com/brainly/style-guide/issues/935
closes https://github.com/brainly/style-guide/issues/936
> Add xxsmall and light modifier to icon-as-button

- package.json
- src/components/buttons/_buttons-mixins.scss
solution found here: http://stackoverflow.com/questions/35464067/flexbox-not-working-on-button-element-in-some-browsers/40483475#40483475
before:
after:
> Add hack for Safari inline-flex on buttons issue

- package.json
- src/components/layout/_layout.scss
using `flex-basis: 1px;` here was related to jumping two-column layout.
checked on chrome and firefox: layout is not jumping anymore without `flex-basic: 1px;`
IE11 before:
IE11 after:
> Remove flex-basis: 1px; from layout content (IE11 issue)

- package.json
- src/components/toplayer/_toplayer.scss
- src/components/toplayer/small_spaced_toplayer.html
- src/components/toplayer/splash_screen_toplayer.html
- src/components/toplayer/toplayer.html
closes https://github.com/brainly/style-guide/issues/962
closes https://github.com/brainly/style-guide/issues/958
> Add modifiers to toplayer

- scripts/tasks/build-react-pages.js
now generated HTML files from react additionally move to _includes folder for jekyll
eslint formating
> fix react jekyll build

- package.json
- src/components/flash-messages/_flash-messages.scss
Before:
After:
Fixed issue #3391
> Add padding for flash message

- package.json
- src/components/buttons/_buttons-mixins.scss
> disabed button fix

- package.json
- src/components/badges/pages/badges-interactive.jsx
- src/components/bubble/pages/bubble-interactive.jsx
- src/components/buttons/pages/buttons-interactive.jsx
- src/components/separators/pages/separators-interactive.jsx
- src/components/stickers/pages/stickers-interactive.jsx
- src/components/subject-icons/pages/subject-icons-interactive.jsx
> dark docs active block bg for some interactive components

- package.json
- src/components/action-list/ActionList.jsx
- src/components/action-list/ActionList.spec.jsx
- src/components/action-list/pages/action-list-interactive.jsx
> ActionList directions

- package.json
- src/components/form-elements/_text-input.scss
> firefox transparent placeholder fix

- src/components/toplayer/_toplayer.scss
before:
before (edge case):
after:
> Limit height of toplayer--splash-screen

- package.json
- src/components/toplayer/_toplayer.scss
Reverts brainly/style-guide#1315
issue: not visible content
> Revert "Limit height of toplayer--splash-screen"

- package.json
- src/components/home-button/_home-button.scss
Brainly Plus home-button has the same width as Brainly default home-button.
> Adjust Brainly Plus home-button

- src/components/form-elements/Textarea.jsx
Sadly `enzyme` does not play nice with refs, so no way to test that 😞
> Add `textareaRef` prop

- CONTRIBUTING.md
- package.json
- src/components/action-list/ActionList.spec.jsx
- src/components/action-list/ActionListHole.spec.jsx
- src/components/action-list/pages/action-list-interactive.jsx
- src/components/action-list/pages/action-list.jsx
- src/components/box/pages/box-interactive.jsx
- src/components/box/pages/box.jsx
- src/components/bubble/pages/bubble-interactive.jsx
- src/components/bubble/pages/bubble.jsx
- src/components/buttons/ButtonPrimary.jsx
- src/components/buttons/ButtonPrimary.spec.jsx
- src/components/buttons/ButtonSecondary.jsx
- src/components/buttons/ButtonSecondary.spec.jsx
- src/components/buttons/pages/buttons-interactive.jsx
- src/components/buttons/pages/buttons.jsx
- src/components/content-box/pages/content-box-interactive.jsx
- src/components/content-box/pages/content-box.jsx
- src/components/header/iframe-pages/small-device.jsx
- src/components/header/pages/header-interactive.jsx
- src/components/header/pages/header.jsx
- src/components/popup-menu/pages/popup-menu-interactive.jsx
- src/components/popup-menu/pages/popup-menu.jsx
- src/components/toplayer/iframe-pages/notlogged_toplayer.jsx
- src/components/toplayer/iframe-pages/small_spaced_toplayer.jsx
- src/components/toplayer/pages/toplayer-interactive.jsx
- src/components/toplayer/pages/toplayer.jsx
> Change type into buttonType for buttons

- .babelrc
- package.json
Do not transform modules in babel!
Symfony logged bundle from 821 459 bytes  to 815 115 bytes
> Update babel rc

- src/components/icon-as-button/IconAsButton.jsx
- src/components/icon-as-button/IconAsButton.spec.jsx
- src/components/icon-as-button/pages/icon-as-button-interactive.jsx
IconAsButton will render as a `<a>` when href is passed in as props. Also added `role="button"` for accessibility.
> Added href to IconAsButton

- package.json
- src/components/toplayer/TopLayer.jsx
- src/components/toplayer/TopLayer.spec.jsx
- src/components/toplayer/_toplayer.scss
- src/components/toplayer/pages/toplayer-interactive.jsx
noPadding=false
noPadding=true
> Add no-padding modifier to Toplayer

- package.json
- src/components/form-elements/Textarea.jsx
`PropTypes.string` was only valid for the native `<textarea />`, but not neccessarily for other node `Type`s.
> Fix textarea value PropType

- package.json
- src/components/card/Card.jsx
- src/components/card/_card.scss
- src/components/card/pages/card-interactive.jsx
- src/components/toplayer/TopLayer.jsx
- src/components/toplayer/_toplayer.scss
- src/components/toplayer/pages/toplayer-interactive.jsx
Added to avoid cases like following:
when TopLayer/Card's content has its own background-color and it's rounded
> Add transparent modifier to TopLayer and Card

- package.json
- src/components/rating/Rating.jsx
- src/components/rating/Rating.spec.jsx
- src/components/rating/_rating.scss
- src/components/rating/pages/rating-interactive.jsx
- src/components/rating/pages/rating.jsx
- src/components/rating/subcomponents/RateCounter.jsx
- src/components/rating/subcomponents/RateCounterItem.jsx
- src/components/rating/subcomponents/Star.jsx
- added `LARGE` size, change way the props are setting size,
- removed `SMALL` size,
- added more power: component allows to listen on star events - example usage:
- counter visibility now done in CSS,
- closes https://github.com/brainly/style-guide/issues/1413
- closes https://github.com/brainly/style-guide/issues/1435
**Screenshot**
**Styles change for visual comparison:**
> Upgrade rating component

- package.json
- src/components/rating/_rating.scss
- all elements within component are now back to centered vertical alignment,
- dynamic labels do change properly now (only when you hover stars, not whole component)
**before** (notice label change but stars are not updating - mouse is over label):
**after**:
> Fix rating component

- package.json
- src/components/text/_text-bits.scss
TextBit changes: font-size form 24px to 25px, letter spacing to 0.
now:
was:
> change textbit

- package.json
- src/components/box/Box.jsx
- src/components/box/Box.spec.jsx
- src/components/box/_box.scss
- src/components/box/pages/box-interactive.jsx
- src/components/box/pages/box.jsx
Design for consistent messages for users in case of: disabling some feature in Brainly, "your search include questions with Verified Answers", info about patron of a subject etc.
It is actually a Box with new modifiers: 'message' and 'onClose' - function on 'X' closing a message.
'Message' excludes shadow and different padding - to stay consistent.
Design:
Implementation:
> consistent messages for fallback on feed 

- package.json
- src/components/home-button/HomeButton.jsx
This is short term fix, long term I believe we should stop treating component folder as node path.
> Use relative path for importing logo in home button

- package.json
- src/components/box/Box.jsx
- src/components/box/_box.scss
- src/components/box/pages/box-interactive.jsx
- src/components/box/pages/box.jsx
noBorderRadius will be used in mobile view in patronages, fallback messages, information messages (no private messages, verified answers)
> add no border radius to box and change examples

- package.json
- src/components/form-elements/_select.scss
Change height of selects to be aligned with inputs.
BEFORE:
AFTER:
> Selects same height as inputs

- package.json
- src/components/overlay/_overlay.scss
Toplayer shadow should stay as it is (confirmed with Patrycja)
After:
Before:
> Make overlay blue

- src/components/colors/hex.js
- src/components/colors/hex.spec.js
and now we will be able to import like that:
```javascript
import hex from 'style-guide/src/components/colors/hex';
hex.mintPrimary  // #53cf92
hex.mustardPrimary  // #fec83c
```
> export colors as a hex values

- package.json
- src/components/text/Headline.jsx
- src/components/text/Headline.spec.jsx
- src/components/text/_headlines.scss
- src/components/text/headlineConsts.js
- src/components/text/pages/headlines-interactive.jsx
- src/components/text/pages/headlines.jsx
- src/docs/navigation.js
- src/docs/page-components.jsx
- src/sass/main.scss
**Will be merged as soon as implementation of BIT's is finished**
The second part of refactoring of texts contains:
- new Headline component. It will replace HeaderPrimary and HeaderSecondary. After refactoring in projects and making sure we have a new component in place on production, I will remove Headers from style guide.
- We will support extra-bold for each size of a headline.
- `--light` modifier is replaced with `--white`
- a new component will not have any responsive behavior. I will replace existing headers with 2xheadlines if needed - for small and large screens.
You can have a look on the implementation map here:
> Headline component

- package.json
- src/components/text/_headlines.scss
Bugfix for headline component:
- In the future, we would refactor this mixin or get rid of it
- We will try to not overwrite letter-spacing. It was done in the past as for big headers in bold version. Let's see how it would work for us without it.
- `component` mixing contains min-height that break headlines alignments like in this case:
> BUGFIX - Remove basic component mixin from headline

- package.json
- src/components/text/TextBit.jsx
After consideration - the standard size should be just `sg-text-bit`, we actually don't need to add any additional class for that.
In projects, we would just not add size property when we would like to get standard/default size of the text bit.
In statements it can be used as follows:
`{...(showSmall ? {size: TEXT_BIT_SIZE.SMALL} : {})}`
> Default size should not add any class

- package.json
- src/components/text/TextBit.jsx
- src/components/text/TextBit.spec.jsx
Rollback to a previous version where the default value is exported - seem's like more intuitive also in terms of usage. Normal value does not append a modifier to the class `sg-text-bit`, it just points to this default (just `sg-text-bit`)
Example of usage:
`size={screenInfo.isSmallOnly ? TEXT_BIT_SIZE.SMALL : TEXT_BIT_SIZE.NORMAL}`
> Final fix for BIT

- src/components/text/_headlines.scss
- src/components/text/headlineConsts.js
- src/components/text/pages/headlines.jsx
Colors of headlines should be adjusted to body text, as they can, and sometimes should, appears in pairs. To prevent from using body-text instead of headline, we need to support the same colors as for body text.
> BUGFIX - Headline colors

- package.json
- src/components/card/CardHole.jsx
- src/components/card/_card.scss
- src/components/colors/colors.js
- src/sass/_config.scss
delete unneeded box-shadow in Card (shadow available by props)
new color in Brainly palette graySecondaryUltraLight
> Card changes

- package.json
- src/components/badges/_badges.scss
- src/components/overlayed-box/_overlayed_box.scss
Issue is caused by changes in line-heights in the new text system. The whole feature probably needs to be redesignd, this might be just a short-term solution.
**BEFORE:**
**AFTER:**
> BUGFIX - Badge fix proposal

- package.json
- src/components/overlayed-box/_overlayed_box.scss
Design team decided that we need to move overlay box to the top
> Move overlay box to top

- package.json
- src/components/colors/colors.js
- src/sass/_config.scss
Rollback blue values - after review designers decided that they need more time to make a decision regarding blue palette. We roll back to previous setup with additional dark, that is needed for hovers in buttons.
> Rollback blue setup

- package.json
- src/components/avatar/Avatar.jsx
- src/components/avatar/_avatar.scss
- src/components/buttons/_buttons-mixins.scss
- src/components/form-elements/_select.scss
- src/components/form-elements/_text-input.scss
- src/components/form-elements/_textarea.scss
- src/components/text/Link.jsx
- src/components/text/_links.scss
- src/components/text/_text.scss
- src/components/text/pages/text.jsx
- src/components/text/textConsts.js
After refreshing palette we need to update some components:
- Buttons to use a dark color on inverse version
- option to use dark colors in texts  - e.g used for errors
- valid and invalid selects, inputs and text area to use dark colors
- refresh avatar to use brighter colors
- deep blue links
> Fix components after palette update

- .babelrc
- src/.babelrc.js
added babel v7.x config, with compatibility with v6.x
`.babelrc` will be used by babel 6 until this repo will be upgraded to v7, while all consumers will be able to use styleguide by consuming `.babelrc.js` config
> added babel v7.x config, with compatibility with v6.x

- package.json
- src/images/icons/answer.svg
- src/images/icons/heart.svg
Changes of two icons:
answer icon BEFORE:
answer icon AFTER:
heart icon BEFORE:
heart icon AFTER:
> Replace answer and heart icons

- package.json
- src/components/text/Link.jsx
- src/components/text/pages/text.jsx
I need to fix links unstyled - It's for backward compatibility mainly - to not add default color class, as it breaks hover color. 
Also, a condition in weight is not needed.
> Fix unstyled links

- package.json
- src/components/text/Headline.jsx
- src/components/text/TextBit.jsx
- src/components/text/_headlines.scss
- src/components/text/_text-bits.scss
- src/components/text/headlineConsts.js
- src/components/text/pages/headlines.jsx
- src/components/text/pages/text-bit.jsx
Requested changes in bits and headlines colors:
Implementation:
> Update bit and headline

- package.json
- src/components/form-elements/_select.scss
- src/components/form-elements/_text-input.scss
The font size of inputs and selects should be equal or greater than `16px` for iOS to not zooming. We agreed with design to go with it for all inputs.
> Fix Zooming to Input and Select on Focus in iOS Devices

- package.json
- src/components/buttons/ButtonPrimary.jsx
- src/components/buttons/ButtonSecondary.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/_buttons_primary.scss
- src/components/buttons/_buttons_secondary.scss
- src/components/buttons/pages/buttons-interactive.jsx
- src/components/buttons/pages/buttons.jsx
Intorduction of the new buttons:
- **Primary buttons** - they do not change at all in terms of colors, just adjustments of sizes (buttons are bigger form 36px to 40px) with no shadow, border radius and so on. Additionally, I removed all the peach buttons, as they are not used in any place in the application (neither in JSX or in twig):
BEFORE:
AFTER:
- **Primary buttons inverted** - for this type of the buttons we have the biggest change. Buttons type `INVERSE` and `ALT_INVERSE` were merged into one in terms of the look, `DARK_INVERSE` changes it's styling:
BEFORE:
AFTER:
- **Secondary and secondary small** - these buttons ware merged in terms of the size - they are both 32px now. Regarding styling changes, secondary buttons are exactly the same as the primary once:
BEFORE:
AFTER:
We have …
> Introduce new buttons

- package.json
- src/components/icons/Icon.jsx
to make it possible to use it i.e. in `Label`
```
import Label, {ICON_TYPE} from 'style-guide/src/components/labels/Label';
<Label
iconType={ICON_TYPE.STD_HEART}
/>
```
> Add std-icons to exported icon type

- package.json
- src/components/icons/Icon.jsx
👁 `STD_PONITS` => `STD_POINTS`
> Fix typo in icon name

- package.json
- src/components/icons/Icon.jsx
std-icons started being visible at deprecated icon list...
let's roll it back.
> Rollback: Add std-icons to exported icon type

- package.json
- src/components/avatar/Avatar.jsx
- src/components/avatar/Avatar.spec.jsx
- src/components/avatar/_avatar.scss
- src/components/icons/Icon.jsx
- src/components/icons/_icons.scss
**before**:
**after**:
1. Sizes are updated according to:
2. Default avatar icon (profile) was replaced with a one from a new set (std-profile).
Icon sizes are adjusted too to be aligned with new avatar sizes.
The deprecated sizes will be removed in a separated step.
> Update sizes and default icon of Avatar

- package.json
- src/components/icons/Icon.jsx
- src/components/icons/pages/icons.jsx
It's a second try after rolling back: https://github.com/brainly/style-guide/pull/1603
previously set of std-icons were visible in deprecated set of icons too.
now, there are no visual changes.
**Why this change?**
it's much easier to refactor and replace icons.
it makes it possible to use it i.e. in `Label`
```
import Label, {ICON_TYPE} from 'style-guide/src/components/labels/Label';
<Label
iconType={ICON_TYPE.STD_HEART}
/>
```
> Add std-icons to exported icons type but do not present them in deprecated set

- package.json
- src/components/box/Box.jsx
- src/components/box/pages/box.jsx
- src/components/toplayer/TopLayer.jsx
- src/components/toplayer/pages/toplayer.jsx
> Use std-close instead of x icon in TopLayer and Box

- package.json
- src/components/box/Box.jsx
- src/components/box/_box.scss
- src/components/colors/colors.js
- src/components/colors/pages/colors.jsx
- src/components/flex/Flex.jsx
- src/components/flex/pages/flex.jsx
Fixes #1511 and  fixes #1610
Additionally, the design team asked us to change the namespaces of colors and colors group in our documentation, for now, code names stay without changes, but we would like to align them as well.
BEFORE:
AFTER:
> Fix issues with Flex and Box'

- package.json
- src/components/buttons/_buttons.scss
- src/components/icons/Icon.jsx
- src/components/icons/Icon.spec.jsx
- src/components/icons/pages/icons.jsx
Added to get the possibility to display an icon inside the button's text, like following:
Additionally, adjustment for moving text in button - this issue happens only for Proxima 12px font size.
> Add option to display Icon in text in button

- yarn.lock
I've updated a lot of dependencies (locked in yarn.lock) due to security reasons.
I'm strongly recommend to remove gulp because it is not maintained frequently
> Upgrade dependencies due to vunlerabilities

- src/components/round-buttons/RoundButton.jsx
Change for size of the icon in large RoundButton and color set for easier export to sketch:
> Update sizes of the icons in RoundButtons

- src/components/action-list/pages/action-list.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/content-box/pages/content-box.jsx
- src/components/form-elements/pages/checkbox.jsx
- src/components/form-elements/pages/radio.jsx
- src/components/labels-deprecated/LabelDeprecated.jsx
- src/components/labels-deprecated/LabelDeprecated.spec.jsx
- src/components/labels-deprecated/_labels-deprecated.scss
- src/components/labels-deprecated/pages/labels-deprecated-interactive.jsx
- src/components/labels-deprecated/pages/labels-deprecated.jsx
- src/components/labels-deprecated/subcomponents/LabelDeprecatedIcon.jsx
- src/docs/navigation.js
- src/docs/page-components.jsx
- src/index.js
- src/sass/main.scss
- it's a breaking change
- ultimately `LabelDeprecated` will be removed and components replaced by other ones.
- we wanted to make `Label` namespace free
- as a next step we want to replace current `Badge` namespace with `Label` one
usage:
- `import LabelDepraceted` in React
- `<div class="sg-label-deprecated">` in html
> Rename Label to LabelDeprecated

- src/components/spinner-container/SpinnerContainer.jsx
- src/components/spinner-container/_spinner-container.scss
- src/components/spinner-container/pages/spinner-containers-interactive.jsx
- src/components/spinner-container/pages/spinner-containers.jsx
fixes: https://github.com/brainly/style-guide/issues/1652
before:
after:
> Add fullWidth option to SpinnerContainer

- src/components/form-elements/_textarea.scss
The modifier `short` (with initial `40px` height) and bigger top/bottom paddings result with unwanted inner scroll. Moreover `react-textarea-autosize` has a problem with it.
> Fix Textarea Paddings

- src/components/buttons/_buttons-mixins.scss
- src/components/form-elements/_text-input.scss
- src/components/form-elements/_textarea.scss
- src/components/icon-as-button/_icon-as-button.scss
- src/components/labels/_labels.scss
- src/components/round-buttons/_round-buttons.scss
- remove ```outline: none``` property
- fix hover in IconAsButton on touch devices: change css on `active` instead of `hover` -> hover state stays after mouse click on mobile and it should be visible only during click
Before:
After:
> Remove outline none property and fix hover in IconAsButton on touch devices

- src/components/toplayer/TopLayer.jsx
- src/components/toplayer/TopLayer.spec.jsx
add onKeyDown prop, role and tabIndex to close Icon in TopLayer for accessibility reasons
> add onKeyDown prop, role and tabIndex to close Icon in TopLayer

- src/components/labels/_labels.scss
fixes: https://github.com/brainly/style-guide/issues/1738
> Add default cursor to Label

- package.json
- src/components/counters/_counters.scss
fixing the same issue that we had with `Label`: https://github.com/brainly/style-guide/pull/1740 
no visual changes:
> Add default cursor to Counter

- package.json
- src/components/form-elements/_select.scss
- src/sass/_config.scss
- native `select` element gets proper focus and outline (it was hidden earlier)
- `sg-select` becomes just a container, no more styling needed
- almost no visual changes (removing border from container makes it 2px more narrow)
- tested on various devices
> Improve accessibility of selects

- package.json
- src/components/form-elements/_select.scss
fixes: https://github.com/brainly/style-guide/issues/1748
It was an issues when `<Select />` was wrapped into `<ActionList />` (line-height: 0 😢 )
no visual changes
> Define line-height in Select

- src/components/round-buttons/pages/round-buttons-interactive.jsx
- src/docs/page-components.jsx
there was no way to change an icon of RoundButton due to wrong prop name in settings.
> Fix iconType of RoundButtons on Interactive page

- src/components/buttons/Button.jsx
- src/components/buttons/_buttons.scss
- src/components/buttons/pages/buttons.jsx
- src/docs/_sass/_docs-buttons.scss
Two new types of buttons are introduced here:
- `solid-light`
- `transparent-light`
design handoff: https://app.abstract.com/share/080a3c15-fcf8-4321-9435-a3af0a6d5719?collectionLayerId=b1a1b979-1408-4105-97e5-38858f5008e3&mode=build&selected=root-0952A77D-837A-4003-B99B-27C29F492040&sha=6674e6d6c3b6e9f1da9e6803cfc88f90a6631ac6 (non-public access)
> Add solid-light and transparent-light buttons

- package.json
- src/components/buttons/_buttons.scss
- src/components/buttons/pages/buttons.jsx
- src/docs/_sass/_docs-buttons.scss
additional change (no visual change in doc): make icon color (when `color="adaptive"`) to be taken from button component
> Update hover color of outline and transparent buttons

- package.json
- src/components/buttons/Button.jsx
- src/components/buttons/Button.spec.jsx
- src/components/buttons/_buttons.scss
- src/components/buttons/pages/buttons-interactive.jsx
- src/components/buttons/pages/buttons.jsx
- src/docs/_sass/_docs-buttons.scss
According to "[System of colors for States and Variants of buttons](https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/25198593/System%2Bof%2Bcolors%2Bfor%2BStates%2Band%2BVariants%2Bof%2Bbuttons)":
**Toggle button:**
- we use toggles only for Transparent, Outline and Solid Light.
- the color variant includes: (...) icon color + additional attributes like background / outline.
- the color of text is never changed.
**Toggle button hover:**
- we use toggles only for Transparent, Outline and Solid Light so the same logic for hovers applies
> Add toggle buttons

- src/components/list/_list.scss
it's a tiny change requested by design to improve contrast a bit
> Update color of link in List component

- package.json
- src/components/text/Text.jsx
- src/components/text/Text.spec.jsx
- src/components/text/_text.scss
- src/components/text/pages/text-interactive.jsx
- src/components/text/textConsts.js
closes: https://github.com/brainly/style-guide/issues/1775
2 options added:
- `pre-wrap`
- `pre-line`
ref: https://css-tricks.com/almanac/properties/w/whitespace/
> Add whiteSpace prop to Text

- src/components/breadcrumbs/Breadcrumb.jsx
- src/components/breadcrumbs/_breadcrumbs.scss
- src/components/breadcrumbs/pages/breadcrumbs-interactive.jsx
- src/components/breadcrumbs/pages/breadcrumbs.jsx
Includes:
* display: inline for breadcrumb elements
https://github.com/brainly/style-guide/issues/1796
* possibly fixing Â shown when rendering breadcrumb elements (I say possibly because this error is hard to reproduce. The solution I used brings no visible changes, this is the same `·` character, but it may prevent it from happening again).
https://github.com/brainly/style-guide/issues/1787
Tested on all browsers / devices we usually test on.
> Fixes for breadcrumb elements

- package.json
- src/components/counters/_counters.scss
- src/components/form-elements/_checkbox-radio.scss
requested by Design System Team.
- label, from 22px to 24px
- radio button large, from 36px to 32px
> Update size of coutner and large radio button

- src/components/flex/README.md
Change `x` to `s` for 16px spacing size in doc
> Fix flex spacing doc

- src/components/mobile-icons/MobileIcon.jsx
- src/components/mobile-icons/MobileIcon.spec.jsx
- src/components/mobile-icons/_mobile-icon.scss
requested by Design System team:
to keep the same sizes as basic icons
> Adjust sizes of mobile icons

- package.json
- src/components/form-elements/Radio.jsx
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/pages/radio.jsx
- src/sass/_config.scss
- src/sass/_mixins.scss
according to: https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/33523275/FNC#RADIO-BUTTON (internal brainly doc)
it's a breaking change: renaming of sizes
no visual changes of component:
> Add componentSize mixin and rename sizes of Radio

- src/components/form-elements/Radio.jsx
closes https://github.com/brainly/style-guide/issues/1828
thank you @seahindeniz
> Fix default Radio size

- package.json
- src/components/text/Headline.jsx
- src/components/text/Headline.spec.jsx
- src/components/text/Link.jsx
- src/components/text/Text.jsx
- src/components/text/TextBit.jsx
- src/components/text/TextBit.spec.jsx
- src/components/text/_headlines.scss
- src/components/text/_text-bits.scss
- src/components/text/_text.scss
- src/components/text/headlineConsts.js
- src/components/text/pages/headlines.jsx
- src/components/text/pages/text-bit.jsx
- src/components/text/pages/text.jsx
- src/components/text/textConsts.js
no visual changes
this change applies to `Text`, `Link`, `TextBit` and `Headline` components
> Rename text sizes from normal to medium

- package.json
- src/components/text/Headline.jsx
- src/components/text/Text.jsx
- src/components/text/_headlines.scss
- src/components/text/_text.scss
- src/components/text/headlineConsts.js
- src/components/text/pages/headlines.jsx
- src/components/text/pages/text.jsx
- src/components/text/textConsts.js
> Add xxsmall size to Texts and Headlines

- src/components/box/Box.jsx
Flow is not very great with polymorphic types, they are causing type errors that are hard to fix, example issue: https://github.com/facebook/flow/issues/4196
> Remove polymorphic types from Box

- src/components/search/_search.scss
Closes #1903
Top and bottom spacing of icon is (40px (input height) - 18px(icon)) / 2 = 11px
.sg-search__icon has internal 6px padding + 5px = 11px
> Fix search icon spacing

- src/components/text/Headline.jsx
- src/components/text/_headlines.scss
- src/components/text/headlineConsts.js
- src/components/text/pages/headlines.jsx
This is to enable biggest size for `headlines` which are otherwise overridden in few places in the application.
> Add xxxlarge size to the headline

- README.md
- package.json
- yarn.lock
Package "s3" has been forked to @brainly organization. One of dependencies of this package (graceful-fs) was causing our builds to fail. Since this package is no longer maintained, we decided to fork it and make needed updates. As a long-term solution, we need to switch "s3" package to something more up-to-date.
> Switch to forked library @brainly/s3

- package.json
Side effect flag may have impact on consumers package size after build and we need to have it set to `false`. Style guide itself doesn't have side effect other than css file which is being loaded separately from the package.
> Turn off side effects flag for the package

- .prettierrc.js
- src/sass/_config.scss
- src/sass/_mixins.scss
- src/sass/_utils.scss
- src/sass/main.scss
Add **space between** util for controlling the space between child elements (Lobotomized Owls).
Creates space between children. Ignoring children with `.sg-space-ignore` class
```html
<ul class="sg-space-y-xxl">
<li>1</li>
<li>2</li>
<li class="sg-space-ignore">3</li> 
<li>4</li>
</ul>
```
```html
<ul class="emtpy:sg-space-y-xxl">
<li>1</li>
<li>2</li>
<li class="sg-space-ignore">3</li> 
<li>4</li>
<li></li> 
</ul>
```
`md:sg-space-y-xs`, `lg:sg-space-y-xs`
```html
<ul class="sg-space-y-xs md:sg-space-y-xl lg:sg-space-y-xxl"> 
// ...
</ul>
```
It works in similar way for `empty` variant
```html
<ul class="empty:sg-space-y-xs md:empty:sg-space-y-xl lg:empty:sg-space-y-xxl"> 
// ...
</ul>
```
This approach generates quite a lot of classes. Normally it is easily mitigated by using purge css …
> Add space between util

- src/components/labels/Label.jsx
Changes:
-  unnecessary `type`-based `className` removed
closes: https://github.com/brainly/style-guide/issues/1898
> Fix modifiers in Label

- src/docs/pages/utilities.jsx
Unfortunately beta watch didn't notice I was using the wrong doc type (without global `html_beutify`)
> Fix docs page to the one with injected html beautifier

- src/components/labels/Label.jsx
Use achromatic color variant in label. Achromatic is a default color if not provided (same behaviour like with `default` color name)
> Use achromatic color variant in label

- src/docs/layouts/ItemsInteractivePage.jsx
- src/docs/page-utilities.jsx
- src/docs/pages/interactive.jsx
- src/docs/pages/utilities.jsx
- src/sass/pages/utils/space-between.jsx
Build setup is pretty rigid at the moment and interactive page templates are needed to make active item blocks to work. Previous docs are broken and interactive pages always point to the same bundle.
> Enable multiple interactive pages in docs

- src/components/avatar/_avatar.scss
Removing offset from avatar image. Not sure why it was introduced but we cannot move element by border size here. Normally nested element should be moved by `border` to the right if they were absolutely positioned with `border box` sizing on wrapper.
Please let me know if you are aware what use case was meant to be fixed by that :)
> Remove image offset in avatar

- src/components/avatar/Avatar.jsx
- src/components/avatar/Avatar.spec.jsx
- src/components/avatar/_avatar.scss
Unfortunately html-sketchapp is not able to properly clip background on so many nested elements with svg. I need to move bg color to outer element.
Third time lucky 🍀
> Move background color to outer element (html-sketchapp compat)

- src/sass/_fonts.scss
- src/sass/main.scss
In the spa application we want to directly import scss from style-guide package instead relying on external url to the built css. We still want to link to external resources which are unlikely to change so there should be a way to not import fonts when scss in being processed.
> Add ability to import sg scss without fonts

- src/components/labels/Label.jsx
- src/components/labels/_labels.scss
Change dictated by the needs of the designers. Transparent labels do not have an element that would indicate a visible margin. Therefore, it is a problem when aligning elements on designs.
We remove horizontal padding in transparent labels and let manage the spacing between elements by the parent container.
> Remove horizontal padding for transparent labels

- src/components/accordion/Accordion.jsx
- src/components/accordion/Accordion.spec.jsx
- src/components/accordion/Accordion.stories.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
- src/components/accordion/pages/accordion-interactive.jsx
- src/components/accordion/pages/accordion.jsx
- src/docs/navigation.js
- src/docs/page-components.jsx
- src/index.js
- src/sass/main.scss
Accordion based on accordion compoent from `components/src/ui`:
- changed interface (`spacing` prop uses `sg-spacing-[...]` utility class internally)
- added storybook stories (next docs)
- added current docs. Note: Interactive part has problem related to `useLayoutEffect` for jsx rendering. Current docs don't handle that. I won't fix it as we move to storybook.
- edit: fixed responsiveness of component after expanding
- edit: changed transition function to ease out (which fits better for expanding, for collapsing it's better to have ease in but it's not a big issue)
responsive bug will be fixed in separate pr
> Add Accordion Component

- src/components/accordion/Accordion.spec.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
- set pointer only on accordion item header
- fix issue with turning off hover state after click when mouse is still on hover area
> Accordion update

- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
> Fix padding top in AccordionItem content

- src/components/logo/Logo.jsx
Build generated wrong hash at first time (probably something changed in svg file)
> Fixed logo name hash

- src/components/accordion/Accordion.jsx
- src/components/accordion/Accordion.stories.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
Turned out preventDefault is not needed, what we need is `overflow-anchor: none` 😅
> Fix Accordion item scrolling issue part II

- src/components/form-elements/_select.scss
It's changed to fulfill the following obligation:
"Text can be resized without assistive technology up to 200 percent without loss of content or functionality, except for captions and images of text."
ref: https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html
checked on: chrome, safari, firefox, edge and ie11
moreover, setting `line-height` there didn't result in any visual change for default (100%) size.
**when 200% of text resize**
**when 100% of text size** (no influence)
**when 200% of text resize**
**when 100% of text size** (no influence)
> Select - remove custom line-height (a11y fix)

- src/components/utils/useReducedMotion.js
Apparently on ios12 `window.matchMedia('(prefers-reduced-motion: reduce)')` returns undefined instead of proper match media object (looks like a bug, matchMedia is supported there). We need to have extensive cheking. Additionally `(prefers-reduced-motion)` is added as some devices supports only this shorter form
> Fix reduce motion check

- src/components/utils/useReducedMotion.js
It fixes:
`TypeError: mediaQuery.addEventListener is not a function. (In 'mediaQuery.addEventListener('change', handleChange)', 'mediaQuery.addEventListener' is undefined)` error that is thrown on devices with  iOS v12, but also on desktop ie. Firefox v52.
According to: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener:
> "Older browsers should use addListener instead of addEventListener since MediaQueryList only inherits from EventTarget in newer browsers."
at the same time it should still work for newer browsers.
> Fix reduce motion check vol. 2

- src/components/form-elements/Checkbox.jsx
- src/components/form-elements/Checkbox.spec.jsx
- src/components/form-elements/Checkbox.stories.jsx
- src/components/form-elements/Radio.jsx
- src/components/form-elements/Radio.spec.jsx
- src/components/form-elements/Radio.stories.jsx
- src/components/form-elements/_checkbox-radio.scss
- src/components/form-elements/pages/checkbox-interactive.jsx
- src/components/form-elements/pages/checkbox.jsx
- src/components/form-elements/pages/radio-interactive.jsx
- src/components/form-elements/pages/radio.jsx
This is enabler for further development.
- Adding built-in label to `checkbox` and `radio` components, making upcoming implementation of redesign (almost finished by designer) a bit easier from this point. This is backward compatible with current solution if label is not provided.
- Removing deprecated label from radio and checkbox examples.
> Add label to Radio and Checkbox

- src/components/helpers/pages/rwd.jsx
- src/index.js
- src/sass/_config.scss
- src/sass/_helpers.scss
- src/sass/_mixins.scss
Exposing extra large breakpoint which is part of our design system.
Available as 
- **scss variable: `$breakpointXLarge`**
- **mobile first mixin: `sgResponsive(xl)`** - this should be preferred way. Mobile first approach.
- class: `sg-hide-for-xlarge-up`
- mixin `sgBreakpoint(xlarge-up)` -  this mixin shuld be avoided as it mixes 3 different approaches (strict resolution, mobile first and desktop first)
Notes:
- **`sgBreakpoint`, `sg-hide-for-xxx` classes and `RwdHelper` (uses internally sg-hide) are marked as deprecated**
- I added `large-up` to breakpoint map which is the same as wrongly named `large-only`. I leave `large-only` as it is for backward compatibility but `large-up` should be used from now on.
> Add extra large breakpoint to scss

- scripts/build-types.js
New codemod for inexact PropTypes in TypeScript declaration. 
We treat a lot of components like native ones and inexact type is not enough for TypeScript to handle native properties in Style Guide components.
All inexact types which are PropTypes of a component will result in following definition.
Before change in our `components` package in frontend app.
After change, in `components` package in frontend app.
Outstanding issues are correctly caught problems in code. I will fix them separately.
> Generate correct html attributes.

- scripts/build-types.js
Some prop types definition are defined using union types. For such case we need to traverse all types annotation separately. Types are searched even inside generics like `$ReadOnly<>` - `FileHandlerPropsType` and `IconPropsType` are good examples for such cases.
> Handle union types in generated typescript declaration of PropTypes 

- src/components/accordion/Accordion.spec.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
`title` is type of `React.Node`
For the most common case when `title` is `string`  we wrap it in `Link` component to have default styling:
For other cases we allow it to stretch to the whole width:
> Adjust title prop for AccordionItem

- src/components/file-handler/FileHandler.jsx
- src/components/spinner-container/SpinnerContainer.jsx
- src/components/spinner-container/SpinnerContainer.stories.jsx
- src/components/spinner-container/pages/spinner-containers-interactive.jsx
- src/components/spinner-container/pages/spinner-containers.jsx
- src/components/spinner/Spinner.jsx
- fixed spinner container to reflect new spinner props
- added story for spinner container (this requires types to be defined in related component and not imported from other one)
- Changed the default spinner color to `grey-900`. Previously it was `black` to meet the new loading state in the button, but this is explicitly mapped. Setting it back to grey-900 will make adopting spinner breaking changes a little less painful in the app.
- fix spinner in file handler
> Adjust spinner container to new spinner

- src/images/icons/shield.svg
We need to use different order of points in path to be compatible with nonzero fill. Currently html sketch app doesn't handle properly evenodd. I will keep this fill rule just for marking that this is intended fill rule for this icon.
To make it work I redrawn inner shape to be counterclockwise. 
This is of course to be fixed in `html sketch-app` but It's much bigger task than this and we need new lib exprted pretty soon
> Use path compatible with nonzero fill rule in shield icon

- src/components/form-elements/README.md
- src/components/form-elements/Select.jsx
- src/components/form-elements/Select.spec.jsx
- src/components/form-elements/pages/select-interactive.jsx
- src/components/form-elements/pages/select.jsx
This reverts commit 6650cd555b120b1c1b2b9a21c7b248407412af87.
Extending select component surfaced that we had wrong types previously (people passed to the component properties which weren't handled). Also there is some issues found in in [AskEditor feature which uses select](https://teamcity.z-dn.net/buildConfiguration/Frontend_Monorepo_CommitChecker_JsTests2/808601?).
I am reverting to unblock [this PR](https://github.com/brainly/brainly-frontend/pull/15984).  Extended version will be published in release following reverting one.
> Revert "Extend select with grouped options (#2067)"

- src/components/form-elements/README.md
- src/components/form-elements/Select.jsx
- src/components/form-elements/Select.spec.jsx
- src/components/form-elements/pages/select-interactive.jsx
- src/components/form-elements/pages/select.jsx
Getting back to the grouped options in select component (https://github.com/brainly/style-guide/pull/2067)
Change:
- This reverts commit ba8155b7c71255ce07643168f9efdca3526934ec.
- changed condition for non grouped elements `item.text && item.value` → `item.text || item.value`. This fixes [failing tests](https://teamcity.z-dn.net/buildConfiguration/Frontend_Monorepo_CommitChecker_JsTests2/808601?)
All failing types in the app need to be fixed though. They actually caught wrong usage of the component (we accepted non exact types as an options but additional props weren't passed to the option element)
> Allow grouping of options within select component (fixed)

- src/components/labels/Label.jsx
- src/components/labels/Label.stories.jsx
- src/components/labels/_labels.scss
- src/components/labels/pages/labels.jsx
From now label component is single line of text only and will will trim text if it takes more horizontal space than 100% of container. Ellipsis will be added at the end of trimmed text. 
I was thinking about adding title attribute to have access to full text when trimmed but I wasn't sure whether it can conflict with tooltips. Could you add some thoughts?
Since I'm fairly new in the team I've been thinking about other solution but not sure if it fits principles. Let me explain in few points:
1. Add option (via prop) to Text component to be single line only
2. Use single line Text on  Label component, since it's using Text
Fixes #2068
> Trim long texts in Label

- src/components/text/Headline.jsx
- src/components/text/Headline.stories.jsx
- src/components/text/Link.jsx
- src/components/text/Link.stories.jsx
- src/components/text/Text.jsx
- src/components/text/Text.stories.jsx
- src/components/text/_headlines.scss
- src/components/text/_text.scss
- src/components/text/pages/headlines-interactive.jsx
- src/components/text/pages/links-interactive.jsx
- src/components/text/pages/text-interactive.jsx
Text, Link, Headline will now accept new prop `inherited` which makes component styles inherited. This will allow us to nest those components without extra effort of duplicating styles on nested text component.
Example: 
To make nested bold text same colour:
```js
// before
<Text color="mustard">
Some text
<Text color="mustard" weight="bold">bolded part</Text>
</Text>
// after
<Text color="mustard">
Some text
<Text inherited weight="bold">bolded part</Text>
</Text>
```
> nesting Text, Link, Headline with inherited styles

- src/components/text/_text.scss
- `sg-text--black` class sets color to black
> add missing black color class

- src/components/flash-messages/FlashMessage.jsx
- src/components/form-elements/Checkbox.jsx
- src/components/form-elements/Radio.jsx
- src/components/labels/Label.jsx
- src/components/labels/Label.spec.jsx
- src/components/text/Headline.jsx
- src/components/text/Link.jsx
- src/components/text/Text.jsx
- src/components/text/_headlines.scss
- Link when inherited=true and emphasized=true, then it inherits font-weight (emphasized prop is not anymore overriding)
- Headline - black color class adds missing rules
- Headline - color value 'default' is replaced with 'black'
- Text - color value 'default' is replaced with 'black'
- removed usage of Text with color="default"
- Text does not generate broken class names for size and weight when not passed via props.
> Link, Text, Headline classnames generation

- src/docs/_sass/_docs-active-block.scss
- src/docs/components/DocsActiveBlock.jsx
- DocsActiveBlock is now error boundary and shows errors beneath component
Fixes #1926
> catch and show Input errors

- src/components/icons/Icon.jsx
- src/components/icons/_icons-mixin.scss
It was already specified in `IconTypeType`, but not working
closes https://github.com/brainly/style-guide/issues/2114
usage:
> add navy-blue icon color

- buildspec.yml
We want to have storybook files on root level: Now they are deployed to `.storybook-static` path which is wrong.
> update artifacts path

- scripts/build-types.js
- src/index.js
- icon typings are safer to use, have safer names (not mangled)
- all html attributes can be passed as props
> improve typings

- src/components/file-handler/_file-handler.scss
This change is connected with the bug: https://brainly.atlassian.net/browse/PBUGS-1371
The problem: hook `useAttachmentName` from brainly-frontend repo was used to trim name of the attachment. It checked text height vs container height and removed one char at a time until text height was smaller than container height. In case of very long names, it had to do this operation more than e.g. 50 times (by setting local state), what caused `maximum update depth exceeded` error.
In order to fix that, in the separate PR I'm introducing pure css solution to trim the text (https://github.com/brainly/brainly-frontend/pull/17684). Unfortunately, additional change in styles inside FileHandler is needed to do that. 
I believe that this small update is non-breaking change.
Video showing the changes I …
> Update styles in FileHandler

- src/components/accordion/Accordion.jsx
- src/components/accordion/Accordion.stories.jsx
- src/components/accordion/AccordionItem.jsx
- role `heading` and `headingLevel` prop (default value: `2`) added to `AccordionItem` 
- `aria-disabled` set `true` for expanded item in controlled accordion
> Accordion a11y improvements

- src/components/flex/Flex.jsx
- src/components/flex/Flex.spec.jsx
- src/components/flex/Flex.stories.jsx
- src/components/flex/_flex.scss
This feature introduces responsive props for Flex component. It enables passing multiple of values for prop depending on screen width.
**Object notation**
Breakpoints keys: 'sm', 'md', 'lg', 'xl' (all optional)
`<Flex
marginLeft={{
sm: 's',
lg: 'l'
}}>content</Flex>`
result HTML:
```
<div class="sg-flex sg-flex--margin-left-s lg:sg-flex--margin-left-l">
content
</div>
```
**Array notation**
Breakpoints items (use in the same order): 'sm', 'md', 'lg', 'xl' (all optional, can be null or undefined)
`<Flex marginLeft={['s', 'm', null, 'l']}>content</Flex>`
result HTML:
```
<div class="sg-flex sg-flex--margin-left-s md:sg-flex--margin-left-m xl:sg-flex--margin-left-l">
content
</div>
```
List of supported responsive props:
- fullWidth
- fullHeight
- noShrink
- inlineFlex
- alignItems
- …
> Flex responsive props

- src/components/accordion/Accordion.a11y.spec.jsx
- src/components/accordion/AccordionItem.jsx
- src/components/buttons/_buttons-mixins.scss
- src/components/buttons/_buttons.scss
- src/components/form-elements/_checkbox-radio.scss
- src/components/icon-as-button/IconAsButton.jsx
- src/components/icon-as-button/_icon-as-button.scss
- src/components/icons/Icon.jsx
- src/components/icons/_icons-mixin.scss
- src/components/icons/_icons.scss
- src/components/math-symbols/MathSymbol.jsx
- src/components/math-symbols/_math-symbol-icon.scss
- src/components/mobile-icons/_mobile-icon.scss
- src/components/rating/_rating.scss
- src/components/search/_search.scss
- src/components/subject-icons/SubjectIcon.jsx
- src/components/subject-icons/_subject-icon.scss
- added accessible `title` & `description` props for `Icon`
- added `role` to `svg` in `Icon` (default: `"img"`)
- adjusted colors for high contrast mode (only Windows):
normal colors: 
high contrast mode before change:
high contrast mode after change:
closes: #2035
> A11y improvements icon

- src/components/text/stories/text.stories.mdx
A small fix to remove an unnecessary import that made the entire typography page disappear.
**before:**
**after:**
> Fix typography docs

- .babelrc.js
- package.json
- yarn.lock
Use babel define plugin (similar to webpack define plugin) to replace env variable during package build process. 
The effects of the plugin are as follows:
**source**
```
LOGOS_BASE_URL =
process.env.STORYBOOK_ENV === 'dev' ||
process.env.STORYBOOK_ENV === 'chromatic'
? 'images/logos/'
: 'https://styleguide.brainly.com/images/logos/';
```
**output** (when no STORYBOOK_ENV is defined)
```
LOGOS_BASE_URL = false || false ? 'images/logos/' : 'https://styleguide.brainly.com/images/logos/';
```
> Replace storybook env with const during package build process

- src/components/file-handler/FileHandler.a11y.spec.jsx
- src/components/file-handler/FileHandler.jsx
- src/components/file-handler/FileHandler.spec.jsx
- src/components/file-handler/FileHandler.stories.jsx
- src/components/file-handler/_file-handler.scss
- src/docs/navigation.js
- src/sass/_utils.scss
- src/sass/pages/utils/visually-hidden.jsx
* proper role on interactive element, depending on provided props
* uploaded / loading status hidden visually with `aria-live="polite"`
* a11y tests
* label for close button
* thumbnail/icon hidden from accessibility tree
* link is tabbable, when has `role="button"` and `href` is not provided
[Internal docs](https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/951517464/FileHandler)
> FileHandler a11y imprv

- buildspec-branches.yml
Codebuild is limited when it comes to generating link on status check when publishing storybook preview.
It can generate path: `/branch/{branch_name}` so the easiest way to align it with path from s3 is to change deploy destination from `/branches/` to `/branch/`. 
ℹ️ We still need to wait for automation infra team though, to extend terraform configuration to be able to change this path on status check. This was only tested using AWS console. It can work for know till we apply terraform again.
> update url to storybook preview

- src/components/logo/Logo.a11y.spec.jsx
- src/components/logo/Logo.jsx
- src/components/logo/Logo.spec.jsx
`Logo` a11y improvements - logo has an alt text by default.
[Internal documentation](https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/968589401/Logo+a11y)
> Logo a11y improvements

- src/components/accordion/AccordionItem.jsx
- src/components/dialog/Dialog.a11y.spec.jsx
- src/components/dialog/Dialog.jsx
- src/components/home-button/HomeButton.a11y.spec.jsx
- src/components/home-button/HomeButton.jsx
`HomeButton` a11y improvements: `aria-label` added for a link (defaults to type).
aria-* props renamed to use aria naming convention
[Internal documentation](https://brainly.atlassian.net/wiki/spaces/DesignSystem/pages/968098491/HomeButton+a11y)
> HomeButton a11y improvements

- src/components/counters/_counters.scss
it prevents `Counter` component from shrinking
example from the website (where the counter is shrunken):
(too long button copy is another issue)
after fixing it:
no visually change for default usage of `Counter`:
> Counter - Prevent from shrinking

- src/components/text/_headlines.scss
- src/components/text/_subheadlines.scss
- src/components/text/_text.scss
**Note**:
This changes do not affect style-guide itself from visual perspective and are related only to the specific case: importing exposed mixins to style custom elements.
It's partially related to the reported production bug: https://brainly.atlassian.net/browse/PBUGS-1444
**Case:**
when more than 1 text-related mixin was directly imported in a project:
```
@import '~brainly-style-guide/src/components/text/text';
@import '~brainly-style-guide/src/components/text/headlines';
```
due to usage of the same variable names, they were overriding each other and the values were taken from the one that was imported later.
as a result some body texts received the sizes of headlines:
> Fix text related mixins

- src/components/buttons/Button.jsx
It allows to pass a `ref` to the button component, ie. to set `focus` on a specific button/action.
usage:
```
const ref = React.useRef(null);
<Button type="outline" ref={ref}>Go</Button>
```
**Info:**
Other components that have a similar option now are `Flex` and `Box`.
**Tip:** 
it's easier to review this changes without "whitespace characters" changes: https://github.com/brainly/style-guide/pull/2295/files?w=1
> Button - Add forwardRef

- src/components/text/_text.scss
> Texts - Fix for styles of transform prop

- src/components/dialog/Dialog.jsx
- src/components/dialog/Dialog.spec.jsx
Currently both `onEntryTransitionEnd` and `onExitTransitionEnd` callbacks aren't fired when environment doesn't support transition events, e.g. the JSDOM. It requires additional mocking in every test which is not obvious. Furthermore, it doesn't work in older browsers (minor).
- https://github.com/jsdom/jsdom/issues/1781
- https://github.com/testing-library/dom-testing-library/pull/865
> Dialog - Fix Unimplemented TransitionEnd Event

- src/components/accordion/AccordionItem.jsx
- src/components/accordion/_accordion.scss
- src/components/bubble/pages/bubble-interactive.jsx
- src/components/content-box/pages/content-box.jsx
- src/components/file-handler/FileHandler.a11y.spec.jsx
- src/components/file-handler/FileHandler.jsx
- src/components/footer/pages/footer-interactive.jsx
- src/components/footer/pages/footer.jsx
- src/components/form-elements/pages/formElements.jsx
- src/components/icons/Icon.jsx
- src/components/media/pages/media-interactive.jsx
- src/components/media/pages/media.jsx
- src/components/rating/Rating.spec.jsx
- src/components/separators/pages/separators.jsx
- src/components/text/Link.a11y.md
- src/components/text/Link.a11y.spec.jsx
- src/components/text/Link.jsx
- src/components/text/Link.spec.jsx
- src/components/text/Link.stories.jsx
- src/components/text/_text.scss
- src/components/text/pages/links-interactive.jsx
- src/components/utils/generateId.js
- src/components/utils/index.js
- src/sass/_utils.scss
Accessibility improvements in `Link` component: 
- `Link` can work both as button and anchor (`as` prop) with corresponding behaviour pattern:
- `as="a"` (default), when `href` provided: activates on click and enter, is focusable and tabbable, can be disabled (acts like `span`), has focus styles
- `as="button"`: activates on click, enter and space, is focusable and tabbable, can be disabled, has focus styles
- has accessible name (can be overwritten by `aria-label`)
- accessibility documentation
- accessibility tests
More in [documentation](https://github.com/brainly/style-guide/blob/256f28ed4ba541525b240a266d586fc469a078ea/src/components/text/Link.a11y.md)
> Link a11y improvements

- .storybook/main.js
We would like to have controls addon show first and being opened by default.
**Before**
**After**
> Change addons panel order to show contols addon first

- src/components/accordion/Accordion.stories.mdx
- src/components/box/Box.stories.mdx
- src/components/bubble/Bubble.stories.mdx
The purpose of this group was different and I have deviated from the original concept. However, I believe there will still be room for this group in the future.
> Remove "layout" group in storybook

- src/components/box/_box.scss
This change is fixing issue with leaking Box styles to Brainly `main.css` stylesheet and making some Boxes to have invalid border colors
> add includeHtml condition to box styles

- src/components/text/Link.jsx
- src/components/text/Link.stories.mdx
- `hideNewTabIndicator` prop
- remove space between link content and indicator
closes #2395
> Add feature to hide new tab indicator (arrow) in Link

- deprecated.json
- src/components/action-list/pages/action-list-interactive.jsx
- src/components/action-list/pages/action-list.jsx
- src/components/content-box/pages/content-box-interactive.jsx
- src/components/content-box/pages/content-box.jsx
- src/components/header/Header.a11y.spec.jsx
- src/components/header/Header.jsx
- src/components/header/Header.stories.mdx
- src/components/header/HeaderContainer.jsx
- src/components/header/HeaderContent.jsx
- src/components/header/HeaderLeft.jsx
- src/components/header/HeaderMiddle.jsx
- src/components/header/HeaderRight.jsx
- src/components/header/pages/header.jsx
- src/components/header/stories/Header.a11y.mdx
- src/components/icon-as-button/pages/icon-as-button-interactive.jsx
- src/components/icon-as-button/pages/icon-as-button.jsx
- src/components/list/pages/list.jsx
- src/components/popup-menu/pages/popup-menu-interactive.jsx
- src/components/popup-menu/pages/popup-menu.jsx
- src/docs/components/DeprecatedNote.jsx
- src/docs/navigation.js
We decided to deprecate Header. 
- Header deprecated:
- note in old docs added
- a short note in accessibility documentation added
- axe test for Header added
- Header to `deprecated.json` added
- better information in the old documentation about the component being deprecated:
- new component `<DeprecatedNote/>` 
- info on the interactive subpage
> Deprecate Header

- CONTRIBUTING.md
To name an icon, we decided to use `aria-labelledby` instead of `<title/>`. Adding icons process needs to be updated to reflect that decision.
> Update adding icon process

- src/components/counters/Counter.jsx
- src/components/counters/Counters.stories.mdx
- src/components/counters/_counters.scss
- src/components/counters/stories/Counter.a11y.mdx
Darken colors of counter to meet accessibile contrast:
- `blue-50` -> `blue-60`
- `red-50` -> `red-60`
> Darken colors in Counter

- package.json
- scripts/build-types.js
This is fix to other fix https://github.com/brainly/style-guide/pull/2451.
Due to bad regexp some styles are being removed when generating typescript types. I'm narrowing it to only remove React_2 or with other digit.
> fix regex to not remove any styles

- src/components/skip-link/SkipLink.chromatic.stories.jsx
- src/components/skip-link/SkipLink.stories.mdx
Reuse play function within chromatic story to make `SkipLink` component shown up when chromatic screenshot is taken.
> Fix chromatic story for SkipLink

- src/components/transition/CSSTransitionAnimator.js
- src/components/transition/CSSTransitionAnimator.spec.js
- src/components/transition/Transition.jsx
- src/components/transition/Transition.spec.jsx
- src/components/transition/propertyObjectAnimator.js
- src/components/transition/stories/OffsetBehavior.jsx
When `effect` does not define one of the optional phases like `initial`, `animate`, or `exit`, they become "instant" via default values. This is correct behavior for a CSS Transition. For example, when a user doesn't care about the exit transition they skip it but the `onTransitionEnd` callback should be called anyway. The current implementation relies on CSS Transition that doesn't trigger events for transition with a zero duration. It produces a bug when skipped phases won't trigger proper callbacks.
https://user-images.githubusercontent.com/13873576/177271413-fcee004a-b023-40c8-b387-9ab00a7357be.mp4
https://user-images.githubusercontent.com/13873576/177271445-0bd8c1a1-6363-45b2-b6b6-71e6d92eb9a4.mp4
> Transition Component - Fire Callbacks After Instant Animation

- .storybook/preview.js
- src/_docs/blocks/InfoBox.jsx
- src/_docs/blocks/index.js
- src/_docs/styles.scss
- src/components/avatar/stories/Avatar.a11y.mdx
- src/components/card/stories/Card.a11y.mdx
- src/components/flex/Flex.a11y.mdx
- src/components/header/stories/Header.a11y.mdx
- src/components/rating/Rating.a11y.mdx
- src/components/text/Link.a11y.mdx
Default <mark> style doesn't match the new storybook style - it is needed to replace with a custom component InfoBox.
before:
after:
> Replace <mark> with InfoBox component in mdx

- .temp
- scripts/build-s3.js
When version was not changed we were deploying new files from master to latest tagged version. This cause version mismatch and potential bugs when new master has breaking change.
Now version check condition is simplified and build files only when NoSuchKey error is thrown.
> fix unwanted deploys

- src/components/dialog/Dialog.stories.mdx
- src/components/dialog/_dialog.scss
Dialog close button is overlapped by DialogBody causing close button impossible to click.
Adding `z-index` is fixing issue positioning button in proper stacking context
> add z-index for close button to be on top of dialog body

- src/components/spinner/Spinner.jsx
- src/components/spinner/_spinner.scss
- src/components/spinner/stories/Spinner.a11y.mdx
added $blue-60 as a varian to spinner component, because we are going to use it as a placeholder for $blue-60 counter
> Blue 60 color added as a variant to Spinner component

- src/root-redirect.html
This redirect allows someone to use links to stories without version, e.g:
`https://styleguide.brainly.com?path=/story/components-button--default` (it is invalid url)
will redirect to
`https://styleguide.brainly.com/{latest_version}/docs?path=/story/components-button--default`
> redirect to story when no version is in url

- src/components/labels/Label.a11y.spec.jsx
- src/components/labels/Label.jsx
- src/components/labels/stories/Label.a11y.mdx
`iconHidden` does not say clearly enough that it is related to the ARIA, so it is needed to rename it.
> Label: rename iconHidden to iconAriaHidden

- src/components/dialog/DialogOverlay.jsx
Wrap Dialog returned element <> to generate proper type () => JSX.Element
> fix Dialog.Overlay typescript types

- CONTRIBUTING.md
- package.json
- src/components/action-list/ActionList.spec.jsx
- src/components/action-list/ActionListHole.spec.jsx
- src/components/buttons/Button.a11y.spec.jsx
- src/components/buttons/Button.jsx
- src/components/buttons/Button.spec.jsx
- src/components/buttons/Button.stories.mdx
- src/components/buttons/README.md
- src/components/buttons/stories/Button.a11y.mdx
- src/components/dialog/Dialog.stories.mdx
- src/components/dialog/DialogCloseButton.jsx
- src/components/header/Header.stories.mdx
- src/components/header/iframe-pages/small-device.jsx
- src/components/icons/Icon.jsx
- src/components/search/Search.jsx
- src/components/toplayer/iframe-pages/notlogged_toplayer.jsx
- src/components/toplayer/iframe-pages/small_spaced_toplayer.jsx
- src/components/transition/stories/ExpandingDetails.jsx
- src/components/transition/stories/FillMode.jsx
- src/components/transition/stories/FluidList.jsx
- src/components/transition/stories/OffsetBehavior.jsx
- src/components/transition/stories/SharedAxis.jsx
- src/components/transition/stories/StaggeredMotion.jsx
- src/components/transition/stories/TypewriterEffect.jsx
- src/components/transition/stories/common/DummyBox.jsx
`type` prop renamed to `variant` and `nativeType` renamed to `type`. This change allows the developer to use the `type` attribute of the native `button` element.
> Rename Button type to variant

- src/components/buttons/_buttons.scss
In high contrast mode, Buttons should be recognizable as buttons. One popular way is to add a border in each variant of the Button - this also indicates how large the target area is.
> High contrast mode for Button

- src/components/home-button/HomeButton.jsx
HomeButton uses type from Logo for `type` prop but we only need market logos. This change removes other of types.
Closes #2444
> change HomeButton type to accept only brainly market logos

- src/sass/README.md
Change readme to match [real values](https://github.com/brainly/style-guide/blob/master/src/sass/_config.scss#L45).
> doc: fix spacing doc

- src/components/text/_subheadlines.scss
According to https://design.brainly.com/8adfd5f36/p/44cf68-typography/t/97b03b Subheadline should use font weight 400
> fix invalid subheadline font weight

- CONTRIBUTING.md
- scripts/tasks/svgs-generate.js
- svgo.config.js
Update the icons building process with an additional step - removing the “title” node.
> Remove "title" node from svg icons during build

- src/components/dialog/Dialog.jsx
- src/components/dialog/_dialog.scss
There is a need to pass differently styled children and treat a `Dialog` as a functional container, literally an unstyled "window" without its own visual addition... deduplication example in asking a question flow:
https://user-images.githubusercontent.com/13873576/203343672-177e3ce5-4e49-42cf-bf54-e878355f102a.mp4
|appearance="dialog" (default)|appearance="none"|
|-|-|
|<img width="720" alt="Screenshot 2022-11-22 at 15 33 45" src="https://user-images.githubusercontent.com/13873576/203343797-ea2ce9ef-3a33-4b85-a929-a7bbd01f3aa6.png">|<img width="720" alt="Screenshot 2022-11-22 at 15 47 37" src="https://user-images.githubusercontent.com/13873576/203344039-5a1a63e2-fc19-4962-abfa-d428f11c0aec.png">|
[This PR](https://github.com/brainly/style-guide/pull/2471) broke fullscreen behavior by …
> Dialog - Add Appearance Prop

- CONTRIBUTING.md
Adding description for publishing alpha/beta release.
> Update contributing with beta release description

- src/components/form-elements/Select.jsx
It allows to pass a `ref` to the select component, ie. to set `focus`.
usage:
```
const ref = React.useRef(null);
<Select ... ref={ref} />
```
**Info:**
Other components that have a similar option: `Flex`, `Box` and `Button`
**Tip:** 
it's easier to review this changes without "whitespace characters" changes: https://github.com/brainly/style-guide/pull/2588/files?w=1
> Select - Add forwardRef

- src/components/form-elements/Textarea.jsx
It's the same [issue](https://github.com/brainly/style-guide/pull/2550/) we spotted and fixed for `Input` component.
Preview:
https://user-images.githubusercontent.com/1231144/204576617-24321a16-03fb-43ba-bb68-aa52d63fe0f3.mov
> Fix textarea losing focus after error message is displayed

- bin/metrics/cli.js
Metrics CLI is not passing ignore arguments to `main.js`, causing  ignore option not to work. I added this missing argument to main function
> metrics-cli: pass ignore argument to main

- package.json
- tsconfig.json
- yarn.lock
For components using react methods (e.g. forwardRef) there was no typings installed which resulted in fallback to any on that particular type.
This PR additionally upgrades typescript which was not necessary but this is prerequisite step before starting migration to typescript.
> Fix typescript declaration for components using React types (Box, Select, Flex, Button)

- package.json
- scripts/testsPolyfill.js
- src/components/accordion/Accordion.a11y.spec.jsx
- src/components/accordion/Accordion.jsx
- src/components/accordion/stories/rules.a11y.js
- yarn.lock
To be consistent with the a11y rules, Accordion needs an accessible name. It can be provided via `aria-label` or `aria-labelledby`.
> Add label to Accordion

- src/components/text/Link.jsx
it's a follow up to the https://github.com/brainly/style-guide/pull/2616
> Suppress hydration warning on nodes containing a11y related ids vol. 2

- src/components/rating/Rating.jsx
- src/components/rating/_rating.scss
- src/components/rating/subcomponents/Star.jsx
- change spacing between number of votes and stars and between rating and stars from 6px to 4px
- change star type to star_outlined when empty
- fix bug -> '0' visible before rating when it equals 0
**BUG FIX**
Before:
After:
**CHANGED SPACINGS**
Before:
After:
**ACTIVE STATE**
Before:
https://user-images.githubusercontent.com/39903772/210737805-d37681fb-02d3-48e0-be81-088af2b57048.mov
After (UI for active is done as it's in the custom `Rating` component on QPage currently):
https://user-images.githubusercontent.com/39903772/210737818-edda2c7f-8df9-4e92-8117-3f22e7ca3737.mov
> Change Rating component - change icon type, spacings and UI of active state

- src/components/dialog/_dialog.scss
in order to align with the bottomsheet dialog we use for mobile app there is a suggestion to round the corners to 24px on web as well.
discussed with Michał Skowronek, Maciek Nowak and Olga Wysopal, shown on sharpener.
| before | after |
| -- | -- |
| <img width="532" alt="Screenshot 2023-01-12 at 10 09 07" src="https://user-images.githubusercontent.com/53941885/212026203-102e06b9-e2cf-4911-a3fb-94327f55f31d.png"> | <img width="529" alt="Screenshot 2023-01-12 at 10 09 12" src="https://user-images.githubusercontent.com/53941885/212026224-3fb675f7-f5ec-4340-bc3d-d9c8512b45c7.png"> |
> change dialog bottomsheet border radius

- scripts/build.sh
On dev and prod storybook logotypes were loaded from localhost. Now path is set based on environment
> fix path to logos

- src/components/buttons/Button.tsx
- src/components/buttons/_buttons.scss
- Removing click highlight on ios
- Removing user select for all buttons 
- Handling haptic feedback on js level - onTouchStart/End for safari ios
@clxandstuff this is to fix haptic on ios. I am aware that the newest changes published on beta are in [transparent-hover-haptic-feedback-test](https://github.com/brainly/style-guide/compare/transparent-hover-haptic-feedback-test) so this need to be merged aferwards.
https://user-images.githubusercontent.com/8572321/216069895-ec816460-24f4-4ffc-a81e-3e8a931aec2c.mp4
> Handle haptic feedback for safari ios

- src/components/dialog/DialogCloseButton.tsx
... Use type `button` in dialog close button to avoid side effects related to form submission.
> Use type button in dialog close button

- .github/workflows/integrate.yml
Previously it was a main. Even though both names should work after github renamed default branch name, name should match in gh actions.
> Change action event to trigger on master

- .github/workflows/integrate.yml
Making chromatic project token public, is the only way to allow for running chromatic against external forks.
> Use public chromatic project token to allow external contribution

- src/components/flex/Flex.tsx
- src/components/flex/FlexConsts.ts
- src/components/flex/_flex.scss
We will not generate styles for this prop, and typescript will complain when used.
We changed API, however this shouldn't be real breaking change because there will be no effect on user
> remove baseline as accepted prop for Flex justifyContent

- buildspec-storybook-branches-images.yml
- buildspec-storybook-branches.yml
This is temporary fix until we will be able to use makefile to build from branch.
We have to wait for https://brainly.atlassian.net/browse/AI-2027
> Deploy images on branch builds

- src/components/counters/Counter.tsx
- src/components/counters/Counters.stories.mdx
- src/components/counters/_counters.scss
This PR adds types to counter component, dividing it to `solid` and `light` as we have in label component.
Additionally, it allows to use all the same color sets as we have in label component for `solid` and `light`
> Add colors and types to Counter component

- src/components/flex/Flex.chromatic.stories.tsx
- src/components/flex/Flex.stories.mdx
- src/components/flex/Flex.tsx
- src/components/flex/FlexConsts.ts
- src/components/flex/_flex.scss
Add responsive`flex` prop to Flex component with values: `initial`, `none`, `auto`, <1, 12>.
> Allow Flex component to be flex child

- src/components/icons/Icon.stories.mdx
In case an icon is not added to the named group, we should show "misc" section containing such an icon, otherwise we'll miss that icon during chromatic check.
> Add misc implicit group to the story

- src/components/card-interactive/CardRadioGroup.stories.mdx
> Fix type mismatch in CardRadioGroup Story

- src/components/chip/_chip.scss
> Add no-wrap to chip text

- svgo-config.js
Optimize svg paths for storybook views.
Unoptimized svgs may look different than svgs that were optimized using SVGO.
> optimize svg paths in storybook

- src/components/dialog/Dialog.tsx
- src/components/dialog/_dialog.scss
Separate two variants for overlay property:
Light:
Dark:
Business case:
Ads team want to have more focused dialogs when displaying advertisements to users.
> Add overlay property to Dialog

- src/components/dialog/Dialog.stories.mdx
- src/components/dialog/Dialog.tsx
- src/components/dialog/useBodyNoScroll.ts
two dialogs are open. one is nested in another. both are closed at the same time.  `"sg-dialog-no-scroll"` class is not removed from the document body and the whole page cannot be scrolled (due to `manyDialogsOpened` condition).
two dialogs are open. one is nested in another. both are closed at the same time.  `"sg-dialog-no-scroll"` class is removed from the document body and the whole page is working as expected.
**Note:**
An [Issue ](https://github.com/brainly/style-guide/issues/2795) created to introduce an ultimate solution for nested components
> Dialog - useBodyOnScroll - Fix for nested dialogs case

- src/components/select-menu/SelectMenu.tsx
to migitate to following issue:
we used `suppressHydrationWarning` already for some other components in similar cases
FYI - we cannot use useId to solve it, since it's not available in React version currently used here.
> Add suppressHydrationWarning to SelectMenu

- package.json
Our release/versioning process is slightly incorrect. running standard `npm version patch` unexpectedly and automatically pushes changes and "tag" which is also against https://github.com/brainly/style-guide/blob/master/CONTRIBUTING.md#preparing-release
IMO, we should remove that and implement something like https://github.com/marketplace/actions/release-drafter or manually with tools like https://github.com/sindresorhus/np or https://github.com/release-it/release-it
Let me know, what do you think
> 226.0.0 stable release

- src/components/file-handler/FileHandler.tsx
According to a11y rules, link which downloads a file should not have target blank attribute. 
Before:
After:
> Adjust FileHandler by removing target blank attribute.

- src/components/dialog/Dialog.tsx
- src/components/dialog/_dialog.scss
Bug: https://brainly.atlassian.net/browse/NAX-856
Because of `tabIndex: -1` dialog is programmatically focusable and styles from `applyFocus` mixin are changing box-shadow styles. I fixed that by overriding those styles.
https://github.com/user-attachments/assets/7ce7528b-8c0d-46b4-b2fb-6f06b47511e3
https://github.com/user-attachments/assets/d68cc587-acad-4908-933f-ad49f26b2bf3
> Fix focus styles in dialog component

- src/components/dialog/useBodyNoScroll.ts
Problem: when multiple Dialogs were open, body styles got overridden before all modals were closed. As a solution, every modal will keep its initial body class and `top` value and will restore it upon cleanup. 
Before:
https://github.com/user-attachments/assets/87525d00-aee0-4359-8380-68fbb3f26401
After:
Opening sibling modal and nested modal
https://github.com/user-attachments/assets/826a59b9-5ffc-4892-9e0a-fb6ac0fdb83f
Closing 2 modals at the same time (one is nested)
https://github.com/user-attachments/assets/ee5d2dd6-9861-4b91-8416-3e294489039d
Style guide examples:
Uploading Screen Recording 2024-12-04 at 11.59.17.mov…
> Fix overriding body styles when  multiple Dialogs are open

- src/components/dialog/useBodyNoScroll.ts
TS didn't show this as error because `scrollY` is a global variable 🙈 
Problem: wrong `scrollY` value was set in the cleanup function (current one instead of initial), which resulted in scrolling to the top after closing Dialog.
Before:
https://github.com/user-attachments/assets/71386203-9661-4398-a574-58f05ae04fe3
After:
https://github.com/user-attachments/assets/4bfe612f-f3b6-4e6d-93fc-6cf809589209
> Fix issue with scrolling after closing dialog

- src/components/avatar/Avatar.tsx
make wight/height optional number only.
next/image v14+ don't support string for their width/height props.
> chore: update types of AvatarPropsType

- src/components/utils/responsive-props.ts
I believe we should change our build to produce `*.js` + `*.d.ts` instead of delivering `*.ts(s)` files since this causes projects using `style-guilde` to re-build ts files every time, which also triggers checks based on tsconfig of final project.
For now, this is just error suppression to resolve issue in dependent projects
> chore(types): 🏷️ supress type issue

- src/sass/_basics.scss
We can opt out from global focus styles by adding `.sg-no-focus-styles` class to element.
> Exclude specific class from global focus styles

- src/sass/_basics.scss
- src/sass/_focus.scss
Changes included in https://github.com/brainly/style-guide/pull/2837 introduced a bug in Dialog component - dialog wasn't removed from DOM after closing it, overlay was visible and it covered the content below.
**Box-shadow Transitions Interfering with Dialog Removal:** 
When using the :not(.sg-no-focus-styles) selector in `_basics.scss`, the CSS specificity changes. Even though we're not explicitly adding this class to elements, the change in selector impacts how and when transition events fire.
The focus styles apply box-shadow transitions to elements, which conflict with the dialog's own opacity/transform transitions that it uses to detect when to unmount itself. The dialog is looking specifically for the [lastTransitionName](https://github.com/brainly/style-guide/blob/master/src/compon …
> Fix dialog removal from DOM

- src/docs/stories/focus.stories.mdx
The goal for this PR is to fix found typo in `Focus` documentation.
> Fix typo in Focus documentation

- src/components/accordion/Accordion.spec.tsx
- src/components/accordion/Accordion.stories.mdx
- src/components/accordion/Accordion.tsx
- src/components/accordion/stories/Accordion.a11y.mdx
- src/components/accordion/stories/rules.a11y.ts
- Implemented functionality to prevent expansion/collapse via keyboard when disableKeyboardExpansion is true.
- Updated Accordion stories and accessibility documentation to reflect the new prop.
- Enhanced tests to verify keyboard behavior with the new prop.
> Add disableKeyboardExpansion prop to Accordion component
